// Generated by scripts/generate-writing-library-leaf-index.mjs. Do not edit by hand.

export type WritingLeafIndexItem = { slug: string; no: string; title: string };

export const hotspotLeafIndex = {
  "economy": [
    {
      "slug": "high-quality-development",
      "no": "01",
      "title": "高质量发展，关键在“质”不在“量”"
    },
    {
      "slug": "new-quality-productive-forces",
      "no": "02",
      "title": "发展新质生产力，不能只追“新”更要落在“质”"
    },
    {
      "slug": "science-and-technology-innovation",
      "no": "03",
      "title": "让科技创新从“最初一公里”跑到“最后一公里”"
    },
    {
      "slug": "modern-industrial-system",
      "no": "04",
      "title": "建设现代化产业体系，既要老树新枝也要新苗成林"
    },
    {
      "slug": "low-altitude-economy",
      "no": "05",
      "title": "低空经济起飞，更要让产业“飞得稳、飞得远”"
    },
    {
      "slug": "expand-domestic-demand",
      "no": "06",
      "title": "扩大内需，不能只“促一时消费”更要增强长期信心"
    },
    {
      "slug": "unified-national-market",
      "no": "07",
      "title": "建设全国统一大市场，统一的是规则，激活的是活力"
    },
    {
      "slug": "regional-coordinated-development",
      "no": "08",
      "title": "区域协调发展，不是“齐步走”而是“各展所长、彼此成就”"
    },
    {
      "slug": "private-economy-confidence",
      "no": "09",
      "title": "支持民营经济发展，既要政策有力度更要预期有稳定度"
    },
    {
      "slug": "effective-market-proactive-government",
      "no": "10",
      "title": "有效市场和有为政府，不是谁替代谁，而是谁把自己的事做好"
    }
  ],
  "innovation": [
    {
      "slug": "artificial-intelligence",
      "no": "01",
      "title": "人工智能越强大，越要回答“为谁所用、如何善用”"
    },
    {
      "slug": "generative-ai",
      "no": "02",
      "title": "生成式AI改变的是工具，更考验人的判断"
    },
    {
      "slug": "robots",
      "no": "03",
      "title": "机器人从“炫技”到“干活”，场景才是真正赛场"
    },
    {
      "slug": "platform-economy",
      "no": "04",
      "title": "平台经济要有创新活力，也要有规则边界"
    },
    {
      "slug": "new-employment",
      "no": "05",
      "title": "让“从新者”安心，让新就业既灵活也有保障"
    },
    {
      "slug": "new-media",
      "no": "06",
      "title": "新媒体时代，传播可以更快但不能失真"
    },
    {
      "slug": "digital-culture",
      "no": "07",
      "title": "数字文化，让传统“触网”更要让价值“入心”"
    },
    {
      "slug": "smart-society",
      "no": "08",
      "title": "迈向智慧社会，技术越聪明越要让生活更简单"
    },
    {
      "slug": "data-elements",
      "no": "09",
      "title": "激活数据要素，关键不是“数据越多越好”而是“流得动、用得好、守得住”"
    },
    {
      "slug": "algorithm-governance",
      "no": "10",
      "title": "算法越深入生活，越要让规则“看得见、说得清、改得了”"
    }
  ],
  "livelihood": [
    {
      "slug": "employment",
      "no": "01",
      "title": "稳就业，不只要有岗位，更要有质量"
    },
    {
      "slug": "talent",
      "no": "02",
      "title": "人才工作，不能止于“抢人”更要善于“成就人”"
    },
    {
      "slug": "education",
      "no": "03",
      "title": "办好人民满意的教育，既要公平也要优质"
    },
    {
      "slug": "health",
      "no": "04",
      "title": "健康中国，要从“治已病”走向“护全程”"
    },
    {
      "slug": "elderly-care",
      "no": "05",
      "title": "养老服务，既要兜住基本也要回应品质"
    },
    {
      "slug": "old-and-young",
      "no": "06",
      "title": "托稳“一老一小”，就是托稳万千家庭的日常"
    },
    {
      "slug": "invest-in-people",
      "no": "07",
      "title": "“投资于人”，投的是当下民生，更是未来发展"
    },
    {
      "slug": "birth-support-system",
      "no": "08",
      "title": "完善生育支持，不能只谈“愿不愿生”更要回应“养得起、带得好”"
    },
    {
      "slug": "vocational-education",
      "no": "09",
      "title": "职业教育，不是“低一等的选择”而是成才的重要赛道"
    },
    {
      "slug": "social-security-safety-net",
      "no": "10",
      "title": "织密社会保障网，既要兜住困难也要托起发展信心"
    }
  ],
  "ecology": [
    {
      "slug": "sponge-city",
      "no": "01",
      "title": "建设海绵城市，让城市既会“呼吸”也能“应急”"
    },
    {
      "slug": "green-low-carbon-transition",
      "no": "02",
      "title": "绿色转型，不是发展的“减速键”而是增长方式的“换挡键”"
    },
    {
      "slug": "beautiful-china",
      "no": "03",
      "title": "建设美丽中国，既要天蓝水清也要百姓可感"
    },
    {
      "slug": "carbon-peak-neutrality",
      "no": "04",
      "title": "实现“双碳”目标，急不得也等不得"
    },
    {
      "slug": "eco-civilization-system",
      "no": "05",
      "title": "生态文明建设，靠一时用力更靠制度管长远"
    },
    {
      "slug": "eco-product-value",
      "no": "06",
      "title": "绿水青山变成金山银山，要靠机制不能靠等待"
    },
    {
      "slug": "biodiversity",
      "no": "07",
      "title": "保护生物多样性，守的是自然家底也是发展底线"
    },
    {
      "slug": "pollution-control",
      "no": "08",
      "title": "打好污染防治攻坚战，越到后期越要盯住细处"
    },
    {
      "slug": "waste-sorting-circular",
      "no": "09",
      "title": "垃圾分类难在坚持，贵在把废物变成资源"
    },
    {
      "slug": "desertification-control",
      "no": "10",
      "title": "治沙造林，比种下去更难的是活下来"
    }
  ],
  "culture": [
    {
      "slug": "cultural-confidence",
      "no": "01",
      "title": "坚定文化自信，更要把自信写进生活"
    },
    {
      "slug": "traditional-culture",
      "no": "02",
      "title": "让优秀传统文化在今天依然可感、可亲、可用"
    },
    {
      "slug": "cultural-innovation",
      "no": "03",
      "title": "守正不是守旧，创新不能失根"
    },
    {
      "slug": "culture-tourism",
      "no": "04",
      "title": "文旅融合，不能只有“人从众”还要留下文化味"
    },
    {
      "slug": "urban-culture",
      "no": "05",
      "title": "城市文化既要有“面子”，更要有“里子”"
    },
    {
      "slug": "public-culture",
      "no": "06",
      "title": "公共文化服务，既要“送到家”更要“种进心”"
    },
    {
      "slug": "cultural-industry",
      "no": "07",
      "title": "文化产业融合，不能只做“文化贴牌”"
    },
    {
      "slug": "cultural-subjectivity",
      "no": "08",
      "title": "增强文化主体性，既要守住自己的根，也要打开交流的门"
    },
    {
      "slug": "museum-fever",
      "no": "09",
      "title": "从“博物馆热”看文化需求：出圈之后更要把内容做深"
    },
    {
      "slug": "intangible-cultural-heritage",
      "no": "10",
      "title": "非遗传承，传的不是一个“老物件”而是一门活的生活技艺"
    }
  ],
  "civility": [
    {
      "slug": "ideals-faith",
      "no": "01",
      "title": "理想信念，是走远路时最稳的方向感"
    },
    {
      "slug": "dedication",
      "no": "02",
      "title": "无私奉献，不是没有个人选择而是心中装着更大价值"
    },
    {
      "slug": "integrity-innovation",
      "no": "03",
      "title": "守正创新，既不能丢掉根本也不能停在原地"
    },
    {
      "slug": "core-socialist-values",
      "no": "04",
      "title": "培育核心价值观，重在日用而不觉"
    },
    {
      "slug": "citizen-morality",
      "no": "05",
      "title": "公民道德建设，从管好自己的言行做起"
    },
    {
      "slug": "social-credit",
      "no": "06",
      "title": "建设诚信社会，让守信者通行让失信者受限"
    },
    {
      "slug": "changing-customs",
      "no": "07",
      "title": "移风易俗，要减负担更要顺人心"
    },
    {
      "slug": "volunteer-service",
      "no": "08",
      "title": "志愿服务，贵在专业更贵在持久"
    },
    {
      "slug": "family-tradition",
      "no": "09",
      "title": "注重家风建设，家庭的底色决定社会的成色"
    },
    {
      "slug": "online-civility",
      "no": "10",
      "title": "网络文明，屏幕背后同样是真实的人"
    }
  ],
  "cadre": [
    {
      "slug": "investigation-research",
      "no": "01",
      "title": "调查研究，脚下沾泥才能心中有数"
    },
    {
      "slug": "responsibility",
      "no": "02",
      "title": "责任担当，不是逞强蛮干而是该出手时能扛事"
    },
    {
      "slug": "rooted-grassroots",
      "no": "03",
      "title": "扎根基层，不是“熬资历”而是在一线长本事"
    },
    {
      "slug": "struggle-pragmatism",
      "no": "04",
      "title": "奋斗实干，既要肯干也要会干、干成"
    },
    {
      "slug": "mass-line",
      "no": "05",
      "title": "群众路线，走的是脚步更是立场"
    },
    {
      "slug": "correct-performance-view",
      "no": "06",
      "title": "正确政绩观，既看显绩更看潜绩，既看当下更看长远"
    },
    {
      "slug": "learning-and-capability",
      "no": "07",
      "title": "善于学习，学的不是“知识库存”而是解决新问题的能力"
    },
    {
      "slug": "long-termism-nailing-spirit",
      "no": "08",
      "title": "久久为功，难的不是“开始做”而是“一件接着一件做”"
    },
    {
      "slug": "fault-tolerance-mechanism",
      "no": "09",
      "title": "为担当者担当，容错纠错要容得实也纠得准"
    },
    {
      "slug": "young-cadre-growth",
      "no": "10",
      "title": "年轻干部成长，要在吃劲岗位上真正经事"
    }
  ],
  "service": [
    {
      "slug": "streamline-government-services",
      "no": "01",
      "title": "简政放权，不是少管，而是更会管"
    },
    {
      "slug": "one-thing-efficiently",
      "no": "02",
      "title": "“高效办成一件事”，高效的是流程，温暖的是民心"
    },
    {
      "slug": "digital-government",
      "no": "03",
      "title": "数字政府，不能只“上云”更要“入心”"
    },
    {
      "slug": "tight-budget-government",
      "no": "04",
      "title": "政府过紧日子，为的是让百姓过好日子"
    },
    {
      "slug": "business-environment",
      "no": "05",
      "title": "优化营商环境，最好的政策是稳定的预期"
    },
    {
      "slug": "standardized-government-service",
      "no": "06",
      "title": "政务服务标准化规范化便利化，最终都要落到“好办事”"
    },
    {
      "slug": "open-government",
      "no": "07",
      "title": "建设阳光政府，让权力在公开中运行、在监督中规范"
    },
    {
      "slug": "policy-implementation-closed-loop",
      "no": "08",
      "title": "抓落实，不能只看“部署了没有”更要看“问题解决了没有”"
    },
    {
      "slug": "government-service-window",
      "no": "09",
      "title": "窗口服务的温度，藏在办事群众的表情里"
    },
    {
      "slug": "inclusive-public-service",
      "no": "10",
      "title": "公共服务均等化，重点在补上最短的那块板"
    }
  ],
  "grassroots": [
    {
      "slug": "grassroots-governance",
      "no": "01",
      "title": "基层治理，关键是把“最后一公里”走成“最暖一公里”"
    },
    {
      "slug": "four-grassroots",
      "no": "02",
      "title": "“四下基层”，下的是基层，连的是民心"
    },
    {
      "slug": "fengqiao-experience",
      "no": "03",
      "title": "新时代“枫桥经验”，贵在矛盾不上交、服务不缺位"
    },
    {
      "slug": "liuchixiang-method",
      "no": "04",
      "title": "“六尺巷工作法”，让礼让有温度、调解有尺度"
    },
    {
      "slug": "four-governance",
      "no": "05",
      "title": "自治、法治、德治、智治，要各有其位更要协同发力"
    },
    {
      "slug": "grassroots-burden-reduction",
      "no": "06",
      "title": "基层减负，减的是无谓负担，增的是干事效能"
    },
    {
      "slug": "community-governance",
      "no": "07",
      "title": "社区治理，要在“家门口”把民生小事办好"
    },
    {
      "slug": "urban-governance",
      "no": "08",
      "title": "城市治理，要像绣花一样精细，也要像生命体一样协同"
    },
    {
      "slug": "smart-city",
      "no": "09",
      "title": "智慧城市，智慧不只在“屏”上更要在治理中"
    },
    {
      "slug": "refined-city-management",
      "no": "10",
      "title": "精细化治理，要从“差不多”走向“刚刚好”"
    }
  ],
  "enforcement": [
    {
      "slug": "rule-of-law",
      "no": "01",
      "title": "全面依法治国，让法治成为发展最可靠的制度保障"
    },
    {
      "slug": "scientific-legislation",
      "no": "02",
      "title": "科学立法，要让法律立得住、行得通、真管用"
    },
    {
      "slug": "strict-enforcement",
      "no": "03",
      "title": "严格执法，严的是违法行为，守的是公平秩序"
    },
    {
      "slug": "fair-justice",
      "no": "04",
      "title": "公正司法，让公平正义以看得见的方式实现"
    },
    {
      "slug": "law-abiding-society",
      "no": "05",
      "title": "全民守法，让法治从“纸面规则”成为“生活习惯”"
    },
    {
      "slug": "people-centered-enforcement",
      "no": "06",
      "title": "执法为民，既要维护秩序也要守护民生"
    },
    {
      "slug": "flexible-enforcement",
      "no": "07",
      "title": "柔性执法，柔的是方式，不是法律底线"
    },
    {
      "slug": "service-oriented-enforcement",
      "no": "08",
      "title": "服务型执法，服务不是放松监管而是促进守法"
    },
    {
      "slug": "smart-enforcement",
      "no": "09",
      "title": "智慧执法，技术可以提效但不能代替判断"
    },
    {
      "slug": "enforcement-supervision",
      "no": "10",
      "title": "执法监督，要让权力每一次出手都有边界"
    },
    {
      "slug": "enforcement-team",
      "no": "11",
      "title": "高素质执法队伍，既要懂法律也要懂群众"
    }
  ],
  "rural": [
    {
      "slug": "rural-revitalization",
      "no": "01",
      "title": "乡村振兴，振的是产业更是乡村整体活力"
    },
    {
      "slug": "thousand-villages-project",
      "no": "02",
      "title": "读懂“千万工程”，不能只学环境整治的表面"
    },
    {
      "slug": "food-security",
      "no": "03",
      "title": "粮食安全这根弦，丰年也不能松"
    },
    {
      "slug": "harmonious-villages",
      "no": "04",
      "title": "建设和美乡村，既要村容整洁也要人心和顺"
    },
    {
      "slug": "rural-living-environment",
      "no": "05",
      "title": "农村人居环境整治，难在长效不在一次动员"
    },
    {
      "slug": "rural-industry-integration",
      "no": "06",
      "title": "发展乡村产业，要种得好也要卖得好"
    },
    {
      "slug": "rural-talent",
      "no": "07",
      "title": "乡村振兴的关键在人，难点也在人"
    },
    {
      "slug": "rural-culture-revitalization",
      "no": "08",
      "title": "乡村文化振兴，要留住乡愁也要接上时代"
    },
    {
      "slug": "consolidate-poverty-alleviation",
      "no": "09",
      "title": "巩固脱贫成果，防返贫比促增收更需要紧盯"
    },
    {
      "slug": "new-agricultural-entities",
      "no": "10",
      "title": "培育新型农业经营主体，要把小农户带进现代农业"
    }
  ]
} as const satisfies Record<string, readonly WritingLeafIndexItem[]>;

export const caseLeafIndex = {
  "people": [
    {
      "slug": "huang-wenxiu",
      "no": "01",
      "title": "黄文秀：把青春扎进基层一线"
    },
    {
      "slug": "zhang-guimei",
      "no": "02",
      "title": "张桂梅：把一件平凡的事长期做下去"
    },
    {
      "slug": "fan-jinshi",
      "no": "03",
      "title": "樊锦诗：把一生交给敦煌"
    },
    {
      "slug": "yuan-longping",
      "no": "04",
      "title": "袁隆平：把论文写在稻田里"
    },
    {
      "slug": "tu-youyou",
      "no": "05",
      "title": "屠呦呦：从传统典籍中找到现代科学线索"
    },
    {
      "slug": "nan-rendong",
      "no": "06",
      "title": "南仁东：为“中国天眼”守住二十多年的目标"
    },
    {
      "slug": "huang-danian",
      "no": "07",
      "title": "黄大年：把个人选择放进国家需要"
    },
    {
      "slug": "zhong-yang",
      "no": "08",
      "title": "钟扬：把种子和知识留给未来"
    },
    {
      "slug": "qian-qihu",
      "no": "09",
      "title": "钱七虎：把一生研究放在国家安全底座上"
    },
    {
      "slug": "deng-qingming",
      "no": "10",
      "title": "邓清明：二十余年备份，不把“没有上场”当作放弃理由"
    }
  ],
  "practice": [
    {
      "slug": "qianwan-project",
      "no": "01",
      "title": "“千万工程”：一张蓝图为什么能画二十多年"
    },
    {
      "slug": "fengqiao-experience",
      "no": "02",
      "title": "“枫桥经验”：把矛盾化解在离群众最近的地方"
    },
    {
      "slug": "liuchixiang-method",
      "no": "03",
      "title": "“六尺巷工作法”：让传统礼让进入基层治理"
    },
    {
      "slug": "pujiang-experience",
      "no": "04",
      "title": "“浦江经验”：领导干部下访，把矛盾解决在一线"
    },
    {
      "slug": "courtyard-council",
      "no": "05",
      "title": "“小院议事厅”：居民的事让居民坐下来商量"
    },
    {
      "slug": "whistle-report-departments",
      "no": "06",
      "title": "“街乡吹哨、部门报到”：基层发现问题，专业力量协同解决"
    },
    {
      "slug": "villager-discussion",
      "no": "07",
      "title": "“村民说事”：把乡村公共事务摆到桌面上"
    },
    {
      "slug": "points-based-governance",
      "no": "08",
      "title": "积分制治理：把文明乡风从口号变成日常行动"
    },
    {
      "slug": "five-social-linkage",
      "no": "09",
      "title": "“五社联动”：社区不再只靠社区干部单打独斗"
    },
    {
      "slug": "micro-grid-governance",
      "no": "10",
      "title": "微网格治理：把治理触角延伸到楼栋和村组"
    }
  ],
  "city": [
    {
      "slug": "jingdezhen-taoxichuan",
      "no": "01",
      "title": "景德镇陶溪川：老厂房如何长出新业态"
    },
    {
      "slug": "shanghai-15min-life-circle",
      "no": "02",
      "title": "上海“15分钟社区生活圈”：把城市尺度落到人的脚步"
    },
    {
      "slug": "chengdu-park-city",
      "no": "03",
      "title": "成都公园城市：把生态空间嵌入城市生活"
    },
    {
      "slug": "hangzhou-city-brain",
      "no": "04",
      "title": "杭州“城市大脑”：技术要进入真实城市问题"
    },
    {
      "slug": "suzhou-old-city-renewal",
      "no": "05",
      "title": "苏州古城保护：更新城市，也保留生活的纹理"
    },
    {
      "slug": "guangzhou-yongqingfang",
      "no": "06",
      "title": "广州永庆坊：老街区用“微改造”连接新生活"
    },
    {
      "slug": "chongqing-mountain-trails",
      "no": "07",
      "title": "重庆山城步道：把“边角空间”变成公共生活空间"
    },
    {
      "slug": "shenzhen-child-friendly",
      "no": "08",
      "title": "深圳儿童友好城市：用“一米高度”重新看城市"
    },
    {
      "slug": "fuzhou-water-system",
      "no": "09",
      "title": "福州水系治理：治一条河，也要治一座城的系统"
    },
    {
      "slug": "beijing-pocket-parks",
      "no": "10",
      "title": "北京口袋公园：城市品质也藏在家门口的“小空间”"
    }
  ],
  "reform": [
    {
      "slug": "zhejiang-most-one-trip",
      "no": "01",
      "title": "浙江“最多跑一次”：让群众少跑腿，让部门多协同"
    },
    {
      "slug": "beijing-call-response",
      "no": "02",
      "title": "北京“接诉即办”：从解决一件事到治理一类事"
    },
    {
      "slug": "shanghai-one-network",
      "no": "03",
      "title": "上海“一网通办”：数字化先改流程，再改入口"
    },
    {
      "slug": "cross-province-services",
      "no": "04",
      "title": "“跨省通办”：让群众流动，服务也跟着流动"
    },
    {
      "slug": "one-license-one-industry",
      "no": "05",
      "title": "“一业一证”：把多张许可从部门视角重新组合"
    },
    {
      "slug": "certificate-free-services",
      "no": "06",
      "title": "“免证办”：让数据多跑路，群众少找证明"
    },
    {
      "slug": "comprehensive-inspection-once",
      "no": "07",
      "title": "“综合查一次”：监管不能让企业反复迎检"
    },
    {
      "slug": "policy-direct-access",
      "no": "08",
      "title": "政策“直达快享”：好政策不能卡在“不会找、不知道”"
    },
    {
      "slug": "government-service-rating",
      "no": "09",
      "title": "政务服务“好差评”：把评价权交给办事群众"
    },
    {
      "slug": "birth-one-thing",
      "no": "10",
      "title": "“出生一件事”：围绕人生节点重组公共服务"
    }
  ],
  "technology": [
    {
      "slug": "beidou-application",
      "no": "01",
      "title": "北斗规模应用：技术突破还要走完“最后一公里”"
    },
    {
      "slug": "shenzhen-low-altitude",
      "no": "02",
      "title": "深圳低空配送：新产业先从真实场景起飞"
    },
    {
      "slug": "c919-industry",
      "no": "03",
      "title": "C919：一架大飞机背后的系统创新"
    },
    {
      "slug": "change-lunar-project",
      "no": "04",
      "title": "嫦娥探月：重大科技工程是一场系统接力"
    },
    {
      "slug": "tianwen-mars",
      "no": "05",
      "title": "“天问一号”：把探索未知变成可执行的工程任务"
    },
    {
      "slug": "china-space-station",
      "no": "06",
      "title": "中国空间站：把重大工程变成开放的科研平台"
    },
    {
      "slug": "fuxing-highspeed",
      "no": "07",
      "title": "复兴号高铁：自主创新也来自庞大系统的协同升级"
    },
    {
      "slug": "fendouzhe-deepsea",
      "no": "08",
      "title": "“奋斗者”号：向深海要答案，先把关键技术做扎实"
    },
    {
      "slug": "5g-scale-application",
      "no": "09",
      "title": "5G规模应用：新技术要进入工厂、港口和真实生活"
    },
    {
      "slug": "east-data-west-computing",
      "no": "10",
      "title": "“东数西算”：算力布局也要算资源账和协同账"
    }
  ],
  "livelihood": [
    {
      "slug": "community-canteen",
      "no": "01",
      "title": "社区食堂：一顿饭里的公共服务温度"
    },
    {
      "slug": "courier-friendly-community",
      "no": "02",
      "title": "骑手友好社区：让公共服务跟着新职业变化"
    },
    {
      "slug": "youth-night-school",
      "no": "03",
      "title": "青年夜校：公共文化也要跟上年轻人的作息"
    },
    {
      "slug": "family-doctor-contract",
      "no": "04",
      "title": "家庭医生：把健康服务从医院延伸到日常"
    },
    {
      "slug": "long-term-care-insurance",
      "no": "05",
      "title": "长期护理保险：给失能家庭多一层照护支撑"
    },
    {
      "slug": "home-care-bed",
      "no": "06",
      "title": "家庭养老床位：把专业照护服务送进家门"
    },
    {
      "slug": "inclusive-childcare",
      "no": "07",
      "title": "普惠托育：把年轻家庭最缺的时间补回来"
    },
    {
      "slug": "urban-study-room",
      "no": "08",
      "title": "城市书房：公共文化服务也可以“小而近”"
    },
    {
      "slug": "barrier-free-renovation",
      "no": "09",
      "title": "无障碍改造：一段坡道体现一座城市的文明尺度"
    },
    {
      "slug": "youth-station",
      "no": "10",
      "title": "青年驿站：给求职青年一段低成本“落脚期”"
    }
  ],
  "law": [
    {
      "slug": "first-violation-no-penalty",
      "no": "01",
      "title": "“首违不罚”：柔性不是放松，关键是过罚相当"
    },
    {
      "slug": "offsite-supervision",
      "no": "02",
      "title": "非现场监管：技术提效不能替代程序判断"
    },
    {
      "slug": "reasoning-enforcement",
      "no": "03",
      "title": "说理式执法：把法理讲清，也把整改路径讲明"
    },
    {
      "slug": "administrative-discretion-benchmark",
      "no": "04",
      "title": "行政裁量基准：让“同案不同罚”少一点"
    },
    {
      "slug": "full-process-enforcement-recording",
      "no": "05",
      "title": "执法全过程记录：让权力运行留下必要轨迹"
    },
    {
      "slug": "major-enforcement-legal-review",
      "no": "06",
      "title": "重大执法决定法制审核：重要决定先过一道“法治闸门”"
    },
    {
      "slug": "enforcement-publicity",
      "no": "07",
      "title": "行政执法公示：让检查和处罚先把规则讲明白"
    },
    {
      "slug": "compliance-guidance",
      "no": "08",
      "title": "合规指导：把执法从“发现问题”延伸到“帮助改好”"
    },
    {
      "slug": "public-legal-service",
      "no": "09",
      "title": "公共法律服务：让群众遇事有地方问法、用法"
    },
    {
      "slug": "public-interest-litigation",
      "no": "10",
      "title": "公益诉讼：为分散的公共利益增加一道法治守护"
    }
  ],
  "negative": [
    {
      "slug": "repeated-forms",
      "no": "01",
      "title": "重复填表留痕：基层时间为何耗在“证明自己干过”"
    },
    {
      "slug": "one-size-fits-all-governance",
      "no": "02",
      "title": "“一刀切”治理：看似省事，实则增加治理成本"
    },
    {
      "slug": "digital-formalism",
      "no": "03",
      "title": "“指尖上的形式主义”：工具为什么反而成了负担"
    },
    {
      "slug": "vanity-project-warning",
      "no": "04",
      "title": "形象工程：看起来“有政绩”，为什么可能留下真负担"
    },
    {
      "slug": "repeated-enterprise-inspections",
      "no": "05",
      "title": "多头重复检查：监管为什么会变成企业负担"
    },
    {
      "slug": "excessive-landscaping",
      "no": "06",
      "title": "过度景观化：乡村建设不能把生活空间做成“样板间”"
    },
    {
      "slug": "campaign-style-closure",
      "no": "07",
      "title": "运动式“一关了之”：治理不能把复杂问题只剩一个按钮"
    },
    {
      "slug": "data-beautification",
      "no": "08",
      "title": "数据“美颜”：数字好看不等于工作真的变好"
    },
    {
      "slug": "layered-additional-requirements",
      "no": "09",
      "title": "层层加码：为什么越到基层任务反而越“变形”"
    },
    {
      "slug": "meeting-document-formalism",
      "no": "10",
      "title": "以会议落实会议：忙碌为什么可能没有产出"
    }
  ],
  "culture": [
    {
      "slug": "palace-museum-cultural",
      "no": "01",
      "title": "故宫文创：传统文化怎样走进日常"
    },
    {
      "slug": "quanzhou-living-heritage",
      "no": "02",
      "title": "泉州古城：遗产保护不是把城市冻住"
    },
    {
      "slug": "liangzhu-heritage",
      "no": "03",
      "title": "良渚古城遗址：让考古成果成为理解文明的入口"
    },
    {
      "slug": "beijing-central-axis",
      "no": "04",
      "title": "北京中轴线：保护的是建筑序列，也是城市历史秩序"
    },
    {
      "slug": "only-green-dance",
      "no": "05",
      "title": "《只此青绿》：传统审美如何转化成当代表达"
    },
    {
      "slug": "china-festival-series",
      "no": "06",
      "title": "“中国节日”节目：让传统节日进入年轻人的屏幕"
    },
    {
      "slug": "intangible-heritage-workshops",
      "no": "07",
      "title": "非遗工坊：让传承技艺也能创造就业和收入"
    },
    {
      "slug": "yin-ruins-museum",
      "no": "08",
      "title": "殷墟博物馆：把考古知识从“专业现场”带到公众面前"
    },
    {
      "slug": "xian-city-wall",
      "no": "09",
      "title": "西安城墙：历史遗产也可以成为日常公共文化空间"
    },
    {
      "slug": "ancient-books-digitization",
      "no": "10",
      "title": "古籍数字化：让珍贵典籍少翻一页，也能多被看见一次"
    }
  ],
  "rural": [
    {
      "slug": "yucun-two-mountains",
      "no": "01",
      "title": "浙江余村：从“卖石头”到“卖风景”"
    },
    {
      "slug": "xiadang-rural",
      "no": "02",
      "title": "福建下党乡：越是基础薄弱，越要从小事做起"
    },
    {
      "slug": "shibadong-village",
      "no": "03",
      "title": "十八洞村：精准帮扶先从“这个村真正缺什么”问起"
    },
    {
      "slug": "shouguang-vegetables",
      "no": "04",
      "title": "寿光蔬菜：一棵菜背后是技术、市场和物流体系"
    },
    {
      "slug": "anji-white-tea",
      "no": "05",
      "title": "安吉白茶：“一片叶子”如何连接生态和富民产业"
    },
    {
      "slug": "liuzhou-luosifen",
      "no": "06",
      "title": "柳州螺蛳粉：地方小吃也能带动一条产业链"
    },
    {
      "slug": "shaxian-snacks",
      "no": "07",
      "title": "沙县小吃：小餐饮背后的创业服务网络"
    },
    {
      "slug": "caoxian-ecommerce",
      "no": "08",
      "title": "曹县电商：数字平台怎样连接县域制造和全国市场"
    },
    {
      "slug": "xiajiang-village",
      "no": "09",
      "title": "浙江下姜村：从单村发展走向片区共同发展"
    },
    {
      "slug": "gutian-edible-fungi",
      "no": "10",
      "title": "古田食用菌：特色农业也要靠科技和标准升级"
    }
  ],
  "ecology": [
    {
      "slug": "saihanba",
      "no": "01",
      "title": "塞罕坝：把荒原一代代种成林海"
    },
    {
      "slug": "yangtze-fishing-ban",
      "no": "02",
      "title": "长江十年禁渔：一条禁令背后的系统治理"
    },
    {
      "slug": "kubuqi-desert-control",
      "no": "03",
      "title": "库布其治沙：生态治理是一场跨越很多年的接力"
    },
    {
      "slug": "sanjiangyuan-national-park",
      "no": "04",
      "title": "三江源国家公园：保护完整生态系统，而不是只保护几个景点"
    },
    {
      "slug": "shenzhen-mangrove",
      "no": "05",
      "title": "深圳红树林：城市越密集，越需要给自然留下空间"
    },
    {
      "slug": "erhai-lake-governance",
      "no": "06",
      "title": "洱海保护：治湖先治岸，治水也要治生产生活方式"
    },
    {
      "slug": "qinling-protection",
      "no": "07",
      "title": "秦岭生态保护：生态红线必须成为真正的硬约束"
    },
    {
      "slug": "yellow-river-delta-wetland",
      "no": "08",
      "title": "黄河三角洲湿地：生态修复要给候鸟和自然过程留空间"
    },
    {
      "slug": "ningxia-straw-checkerboard",
      "no": "09",
      "title": "麦草方格治沙：小办法背后是对自然规律的理解"
    },
    {
      "slug": "chishui-river-protection",
      "no": "10",
      "title": "赤水河保护：一条河需要上下游一起守"
    }
  ],
  "enterprise": [
    {
      "slug": "haier-industrial-internet",
      "no": "01",
      "title": "海尔工业互联网：传统制造也能长出新动能"
    },
    {
      "slug": "catl-innovation",
      "no": "02",
      "title": "宁德时代：越是热门赛道，越要靠研发站稳"
    },
    {
      "slug": "huawei-longterm-rd",
      "no": "03",
      "title": "华为研发投入：企业创新不能只算眼前利润账"
    },
    {
      "slug": "byd-new-energy",
      "no": "04",
      "title": "比亚迪新能源转型：技术路线要靠长期研发和市场检验"
    },
    {
      "slug": "dji-drones",
      "no": "05",
      "title": "大疆无人机：把核心技术做深，再把场景做宽"
    },
    {
      "slug": "midea-smart-manufacturing",
      "no": "06",
      "title": "美的智能制造：传统制造也能长出“数字新能力”"
    },
    {
      "slug": "fuyao-glass",
      "no": "07",
      "title": "福耀玻璃：在一个细分行业把质量和技术做深"
    },
    {
      "slug": "geely-rd",
      "no": "08",
      "title": "吉利汽车：从制造产品走向积累研发平台能力"
    },
    {
      "slug": "sany-smart-factory",
      "no": "09",
      "title": "三一重工智能工厂：工程机械也要从“制造”走向“智造”"
    },
    {
      "slug": "longi-photovoltaic",
      "no": "10",
      "title": "隆基绿能：光伏产业竞争最终要回到技术和成本"
    }
  ]
} as const satisfies Record<string, readonly WritingLeafIndexItem[]>;
