// Generated by scripts/generate-writing-library-leaf-index.mjs. Do not edit by hand.

export type WritingLeafIndexItem = { slug: string; no: string; title: string };

export const hotspotLeafIndex = {
  "economy": [
    {
      "slug": "high-quality-development",
      "no": "01",
      "title": "高质量发展，关键在“质”不在“量”"
    },
    {
      "slug": "new-quality-productive-forces",
      "no": "02",
      "title": "发展新质生产力，不能只追“新”更要落在“质”"
    },
    {
      "slug": "science-and-technology-innovation",
      "no": "03",
      "title": "让科技创新从“最初一公里”跑到“最后一公里”"
    },
    {
      "slug": "modern-industrial-system",
      "no": "04",
      "title": "建设现代化产业体系，既要老树新枝也要新苗成林"
    },
    {
      "slug": "low-altitude-economy",
      "no": "05",
      "title": "低空经济起飞，更要让产业“飞得稳、飞得远”"
    },
    {
      "slug": "expand-domestic-demand",
      "no": "06",
      "title": "扩大内需，不能只“促一时消费”更要增强长期信心"
    },
    {
      "slug": "unified-national-market",
      "no": "07",
      "title": "建设全国统一大市场，统一的是规则，激活的是活力"
    },
    {
      "slug": "regional-coordinated-development",
      "no": "08",
      "title": "区域协调发展，不是“齐步走”而是“各展所长、彼此成就”"
    },
    {
      "slug": "private-economy-confidence",
      "no": "09",
      "title": "支持民营经济发展，既要政策有力度更要预期有稳定度"
    },
    {
      "slug": "effective-market-proactive-government",
      "no": "10",
      "title": "有效市场和有为政府，不是谁替代谁，而是谁把自己的事做好"
    },
    {
      "slug": "manufacturing-digitalization",
      "no": "11",
      "title": "智改数转，制造业要的不是热闹而是实效"
    },
    {
      "slug": "county-economy",
      "no": "12",
      "title": "县域经济，拼的是特色不是雷同"
    },
    {
      "slug": "industrial-chain-security",
      "no": "13",
      "title": "产业链安全，靠的是补短板不是喊口号"
    },
    {
      "slug": "service-manufacturing-fusion",
      "no": "14",
      "title": "先进制造与现代服务业，谁也离不开谁"
    },
    {
      "slug": "foreign-trade-new-three",
      "no": "15",
      "title": "外贸新动能，藏在结构的升级里"
    },
    {
      "slug": "future-industry",
      "no": "16",
      "title": "未来产业，今天就要开始播种"
    },
    {
      "slug": "ice-snow-economy",
      "no": "17",
      "title": "冰雪经济，别让热度融化在春天里"
    },
    {
      "slug": "silver-economy",
      "no": "18",
      "title": "银发经济，既要事业温度也要产业眼光"
    },
    {
      "slug": "ocean-economy",
      "no": "19",
      "title": "经略海洋，向蓝色国土要发展空间"
    },
    {
      "slug": "brand-power",
      "no": "20",
      "title": "品牌建设，中国制造的成人礼"
    }
  ],
  "innovation": [
    {
      "slug": "artificial-intelligence",
      "no": "01",
      "title": "人工智能越强大，越要回答“为谁所用、如何善用”"
    },
    {
      "slug": "generative-ai",
      "no": "02",
      "title": "生成式AI改变的是工具，更考验人的判断"
    },
    {
      "slug": "robots",
      "no": "03",
      "title": "机器人从“炫技”到“干活”，场景才是真正赛场"
    },
    {
      "slug": "platform-economy",
      "no": "04",
      "title": "平台经济要有创新活力，也要有规则边界"
    },
    {
      "slug": "new-employment",
      "no": "05",
      "title": "让“从新者”安心，让新就业既灵活也有保障"
    },
    {
      "slug": "new-media",
      "no": "06",
      "title": "新媒体时代，传播可以更快但不能失真"
    },
    {
      "slug": "digital-culture",
      "no": "07",
      "title": "数字文化，让传统“触网”更要让价值“入心”"
    },
    {
      "slug": "smart-society",
      "no": "08",
      "title": "迈向智慧社会，技术越聪明越要让生活更简单"
    },
    {
      "slug": "data-elements",
      "no": "09",
      "title": "激活数据要素，关键不是“数据越多越好”而是“流得动、用得好、守得住”"
    },
    {
      "slug": "algorithm-governance",
      "no": "10",
      "title": "算法越深入生活，越要让规则“看得见、说得清、改得了”"
    },
    {
      "slug": "chip-self-reliance",
      "no": "11",
      "title": "芯片攻坚，没有捷径只有长跑"
    },
    {
      "slug": "basic-research",
      "no": "12",
      "title": "基础研究，是一切创新的源头活水"
    },
    {
      "slug": "talent-ecosystem",
      "no": "13",
      "title": "人才竞争，比拼的是生态不是口号"
    },
    {
      "slug": "sci-tech-finance",
      "no": "14",
      "title": "科技金融，敢投早投小才有未来"
    },
    {
      "slug": "university-industry",
      "no": "15",
      "title": "产学研融合，堵点在机制不在意愿"
    },
    {
      "slug": "new-rd-institutions",
      "no": "16",
      "title": "新型研发机构，科研与产业之间的摆渡人"
    },
    {
      "slug": "quantum-tech",
      "no": "17",
      "title": "量子科技，抢占未来的制高点"
    },
    {
      "slug": "commercial-space",
      "no": "18",
      "title": "商业航天，从国家任务到市场赛道"
    },
    {
      "slug": "biomedicine",
      "no": "19",
      "title": "创新药出海，中国医药的换挡时刻"
    },
    {
      "slug": "sme-digitalization",
      "no": "20",
      "title": "专精特新，中小企业的冠军之路"
    }
  ],
  "livelihood": [
    {
      "slug": "employment",
      "no": "01",
      "title": "稳就业，不只要有岗位，更要有质量"
    },
    {
      "slug": "talent",
      "no": "02",
      "title": "人才工作，不能止于“抢人”更要善于“成就人”"
    },
    {
      "slug": "education",
      "no": "03",
      "title": "办好人民满意的教育，既要公平也要优质"
    },
    {
      "slug": "health",
      "no": "04",
      "title": "健康中国，要从“治已病”走向“护全程”"
    },
    {
      "slug": "elderly-care",
      "no": "05",
      "title": "养老服务，既要兜住基本也要回应品质"
    },
    {
      "slug": "old-and-young",
      "no": "06",
      "title": "托稳“一老一小”，就是托稳万千家庭的日常"
    },
    {
      "slug": "invest-in-people",
      "no": "07",
      "title": "“投资于人”，投的是当下民生，更是未来发展"
    },
    {
      "slug": "birth-support-system",
      "no": "08",
      "title": "完善生育支持，不能只谈“愿不愿生”更要回应“养得起、带得好”"
    },
    {
      "slug": "vocational-education",
      "no": "09",
      "title": "职业教育，不是“低一等的选择”而是成才的重要赛道"
    },
    {
      "slug": "social-security-safety-net",
      "no": "10",
      "title": "织密社会保障网，既要兜住困难也要托起发展信心"
    },
    {
      "slug": "housing-security",
      "no": "11",
      "title": "住有所居，年轻人不该为一间房耗尽力气"
    },
    {
      "slug": "food-safety",
      "no": "12",
      "title": "食品安全，守住舌尖上的信任"
    },
    {
      "slug": "mental-health",
      "no": "13",
      "title": "心理健康，是健康不可或缺的一半"
    },
    {
      "slug": "barrier-free",
      "no": "14",
      "title": "无障碍环境，丈量城市的良心"
    },
    {
      "slug": "insurance-reform",
      "no": "15",
      "title": "药品集采，把不该花的钱还给患者"
    },
    {
      "slug": "gradual-retirement",
      "no": "16",
      "title": "延迟退休，渐进之中见稳妥"
    },
    {
      "slug": "labor-rights",
      "no": "17",
      "title": "劳动者权益，不能在效率的名义下打折"
    },
    {
      "slug": "youth-employment",
      "no": "18",
      "title": "青年就业，一头连着家庭一头连着未来"
    },
    {
      "slug": "migrants-education",
      "no": "19",
      "title": "随迁子女教育，流动的中国不能让孩子掉队"
    },
    {
      "slug": "long-term-care",
      "no": "20",
      "title": "长期护理保险，为失能老人撑起一片天"
    }
  ],
  "ecology": [
    {
      "slug": "sponge-city",
      "no": "01",
      "title": "建设海绵城市，让城市既会“呼吸”也能“应急”"
    },
    {
      "slug": "green-low-carbon-transition",
      "no": "02",
      "title": "绿色转型，不是发展的“减速键”而是增长方式的“换挡键”"
    },
    {
      "slug": "beautiful-china",
      "no": "03",
      "title": "建设美丽中国，既要天蓝水清也要百姓可感"
    },
    {
      "slug": "carbon-peak-neutrality",
      "no": "04",
      "title": "实现“双碳”目标，急不得也等不得"
    },
    {
      "slug": "eco-civilization-system",
      "no": "05",
      "title": "生态文明建设，靠一时用力更靠制度管长远"
    },
    {
      "slug": "eco-product-value",
      "no": "06",
      "title": "绿水青山变成金山银山，要靠机制不能靠等待"
    },
    {
      "slug": "biodiversity",
      "no": "07",
      "title": "保护生物多样性，守的是自然家底也是发展底线"
    },
    {
      "slug": "pollution-control",
      "no": "08",
      "title": "打好污染防治攻坚战，越到后期越要盯住细处"
    },
    {
      "slug": "waste-sorting-circular",
      "no": "09",
      "title": "垃圾分类难在坚持，贵在把废物变成资源"
    },
    {
      "slug": "desertification-control",
      "no": "10",
      "title": "治沙造林，比种下去更难的是活下来"
    },
    {
      "slug": "yangtze-river-protection",
      "no": "11",
      "title": "长江大保护，共抓才能见效"
    },
    {
      "slug": "yellow-river-basin",
      "no": "12",
      "title": "黄河安澜，重在治水更在治沙"
    },
    {
      "slug": "new-energy-system",
      "no": "13",
      "title": "新型能源体系，既要建得快又要稳得住"
    },
    {
      "slug": "green-lifestyle",
      "no": "14",
      "title": "绿色生活，人人都是行动者"
    },
    {
      "slug": "eco-compensation",
      "no": "15",
      "title": "生态补偿，让保护者不再吃亏"
    },
    {
      "slug": "carbon-dual-control",
      "no": "16",
      "title": "碳排放双控，指挥棒转向之后"
    },
    {
      "slug": "new-pollutants",
      "no": "17",
      "title": "新污染物治理，看不见的风险更要盯住"
    },
    {
      "slug": "urban-green-space",
      "no": "18",
      "title": "推窗见绿，城市最普惠的民生"
    },
    {
      "slug": "central-eco-inspection",
      "no": "19",
      "title": "中央生态环保督察，利剑高悬常鸣"
    },
    {
      "slug": "wetland-protection",
      "no": "20",
      "title": "湿地保护，给自然留一片缓冲的家园"
    }
  ],
  "culture": [
    {
      "slug": "cultural-confidence",
      "no": "01",
      "title": "坚定文化自信，更要把自信写进生活"
    },
    {
      "slug": "traditional-culture",
      "no": "02",
      "title": "让优秀传统文化在今天依然可感、可亲、可用"
    },
    {
      "slug": "cultural-innovation",
      "no": "03",
      "title": "守正不是守旧，创新不能失根"
    },
    {
      "slug": "culture-tourism",
      "no": "04",
      "title": "文旅融合，不能只有“人从众”还要留下文化味"
    },
    {
      "slug": "urban-culture",
      "no": "05",
      "title": "城市文化既要有“面子”，更要有“里子”"
    },
    {
      "slug": "public-culture",
      "no": "06",
      "title": "公共文化服务，既要“送到家”更要“种进心”"
    },
    {
      "slug": "cultural-industry",
      "no": "07",
      "title": "文化产业融合，不能只做“文化贴牌”"
    },
    {
      "slug": "cultural-subjectivity",
      "no": "08",
      "title": "增强文化主体性，既要守住自己的根，也要打开交流的门"
    },
    {
      "slug": "museum-fever",
      "no": "09",
      "title": "从“博物馆热”看文化需求：出圈之后更要把内容做深"
    },
    {
      "slug": "intangible-cultural-heritage",
      "no": "10",
      "title": "非遗传承，传的不是一个“老物件”而是一门活的生活技艺"
    },
    {
      "slug": "cultural-relics-protection",
      "no": "11",
      "title": "文物保护，功在当代利在千秋"
    },
    {
      "slug": "guochao-guofeng",
      "no": "12",
      "title": "国风国潮，文化自信的年轻表达"
    },
    {
      "slug": "online-literature",
      "no": "13",
      "title": "网络文学，从野蛮生长到精品化远航"
    },
    {
      "slug": "red-culture",
      "no": "14",
      "title": "红色文化，把信仰的火种传下去"
    },
    {
      "slug": "reading-for-all",
      "no": "15",
      "title": "全民阅读，书香社会之基"
    },
    {
      "slug": "canal-culture",
      "no": "16",
      "title": "大运河，流动的文化带"
    },
    {
      "slug": "cultural-talent",
      "no": "17",
      "title": "文化人才，传承发展的第一资源"
    },
    {
      "slug": "cultural-consumption",
      "no": "18",
      "title": "文化消费新场景，沉浸其中的吸引力"
    },
    {
      "slug": "art-education",
      "no": "19",
      "title": "美育，不是兴趣班而是必修课"
    },
    {
      "slug": "festival-culture",
      "no": "20",
      "title": "传统节日，刻在时间里的文化基因"
    }
  ],
  "civility": [
    {
      "slug": "ideals-faith",
      "no": "01",
      "title": "理想信念，是走远路时最稳的方向感"
    },
    {
      "slug": "dedication",
      "no": "02",
      "title": "无私奉献，不是没有个人选择而是心中装着更大价值"
    },
    {
      "slug": "integrity-innovation",
      "no": "03",
      "title": "守正创新，既不能丢掉根本也不能停在原地"
    },
    {
      "slug": "core-socialist-values",
      "no": "04",
      "title": "培育核心价值观，重在日用而不觉"
    },
    {
      "slug": "citizen-morality",
      "no": "05",
      "title": "公民道德建设，从管好自己的言行做起"
    },
    {
      "slug": "social-credit",
      "no": "06",
      "title": "建设诚信社会，让守信者通行让失信者受限"
    },
    {
      "slug": "changing-customs",
      "no": "07",
      "title": "移风易俗，要减负担更要顺人心"
    },
    {
      "slug": "volunteer-service",
      "no": "08",
      "title": "志愿服务，贵在专业更贵在持久"
    },
    {
      "slug": "family-tradition",
      "no": "09",
      "title": "注重家风建设，家庭的底色决定社会的成色"
    },
    {
      "slug": "online-civility",
      "no": "10",
      "title": "网络文明，屏幕背后同样是真实的人"
    },
    {
      "slug": "national-honor",
      "no": "11",
      "title": "功勋荣誉表彰，让英雄成为最亮的星"
    },
    {
      "slug": "craftsman-spirit",
      "no": "12",
      "title": "大国工匠，毫厘之间见真章"
    },
    {
      "slug": "honest-business",
      "no": "13",
      "title": "诚信经营，最好的营销是把事做真"
    },
    {
      "slug": "charity-development",
      "no": "14",
      "title": "慈善事业，善意需要制度的护航"
    },
    {
      "slug": "minors-internet",
      "no": "15",
      "title": "未成年人网络保护，为数字原住民护航"
    },
    {
      "slug": "patriotism-education",
      "no": "16",
      "title": "爱国主义教育，凝心聚力的精神工程"
    },
    {
      "slug": "civilized-tourism",
      "no": "17",
      "title": "文明旅游，你即风景"
    },
    {
      "slug": "professional-ethics",
      "no": "18",
      "title": "职业道德，每个行业的隐形契约"
    },
    {
      "slug": "anti-waste",
      "no": "19",
      "title": "厉行节约，反对浪费永远在路上"
    },
    {
      "slug": "mutual-aid",
      "no": "20",
      "title": "凡人善举，社会最动人的底色"
    }
  ],
  "cadre": [
    {
      "slug": "investigation-research",
      "no": "01",
      "title": "调查研究，脚下沾泥才能心中有数"
    },
    {
      "slug": "responsibility",
      "no": "02",
      "title": "责任担当，不是逞强蛮干而是该出手时能扛事"
    },
    {
      "slug": "rooted-grassroots",
      "no": "03",
      "title": "扎根基层，不是“熬资历”而是在一线长本事"
    },
    {
      "slug": "struggle-pragmatism",
      "no": "04",
      "title": "奋斗实干，既要肯干也要会干、干成"
    },
    {
      "slug": "mass-line",
      "no": "05",
      "title": "群众路线，走的是脚步更是立场"
    },
    {
      "slug": "correct-performance-view",
      "no": "06",
      "title": "正确政绩观，既看显绩更看潜绩，既看当下更看长远"
    },
    {
      "slug": "learning-and-capability",
      "no": "07",
      "title": "善于学习，学的不是“知识库存”而是解决新问题的能力"
    },
    {
      "slug": "long-termism-nailing-spirit",
      "no": "08",
      "title": "久久为功，难的不是“开始做”而是“一件接着一件做”"
    },
    {
      "slug": "fault-tolerance-mechanism",
      "no": "09",
      "title": "为担当者担当，容错纠错要容得实也纠得准"
    },
    {
      "slug": "young-cadre-growth",
      "no": "10",
      "title": "年轻干部成长，要在吃劲岗位上真正经事"
    },
    {
      "slug": "clean-self-discipline",
      "no": "11",
      "title": "廉洁自律，从政的第一粒扣子"
    },
    {
      "slug": "cadre-assessment",
      "no": "12",
      "title": "干部考核，指挥棒决定着方向"
    },
    {
      "slug": "duty-sinking",
      "no": "13",
      "title": "干部下沉，沉下去更要融进去"
    },
    {
      "slug": "lying-flat-rectification",
      "no": "14",
      "title": "整治躺平式干部，让实干者不吃亏"
    },
    {
      "slug": "governance-capability",
      "no": "15",
      "title": "治理能力，干部的必修课与常修课"
    },
    {
      "slug": "strictness-kindness",
      "no": "16",
      "title": "严管厚爱，一体两面的组织温度"
    },
    {
      "slug": "style-construction",
      "no": "17",
      "title": "作风建设，永远在路上没有休止符"
    },
    {
      "slug": "grassroots-incentive",
      "no": "18",
      "title": "基层干部，既要压担子也要搭台子"
    },
    {
      "slug": "cadre-exchange",
      "no": "19",
      "title": "干部交流，在多岗位历练中长本事"
    },
    {
      "slug": "media-response",
      "no": "20",
      "title": "舆情素养，干部的新时代基本功"
    }
  ],
  "service": [
    {
      "slug": "streamline-government-services",
      "no": "01",
      "title": "简政放权，不是少管，而是更会管"
    },
    {
      "slug": "one-thing-efficiently",
      "no": "02",
      "title": "“高效办成一件事”，高效的是流程，温暖的是民心"
    },
    {
      "slug": "digital-government",
      "no": "03",
      "title": "数字政府，不能只“上云”更要“入心”"
    },
    {
      "slug": "tight-budget-government",
      "no": "04",
      "title": "政府过紧日子，为的是让百姓过好日子"
    },
    {
      "slug": "business-environment",
      "no": "05",
      "title": "优化营商环境，最好的政策是稳定的预期"
    },
    {
      "slug": "standardized-government-service",
      "no": "06",
      "title": "政务服务标准化规范化便利化，最终都要落到“好办事”"
    },
    {
      "slug": "open-government",
      "no": "07",
      "title": "建设阳光政府，让权力在公开中运行、在监督中规范"
    },
    {
      "slug": "policy-implementation-closed-loop",
      "no": "08",
      "title": "抓落实，不能只看“部署了没有”更要看“问题解决了没有”"
    },
    {
      "slug": "government-service-window",
      "no": "09",
      "title": "窗口服务的温度，藏在办事群众的表情里"
    },
    {
      "slug": "inclusive-public-service",
      "no": "10",
      "title": "公共服务均等化，重点在补上最短的那块板"
    },
    {
      "slug": "enterprise-service",
      "no": "11",
      "title": "企业服务专员，把服务送进车间里"
    },
    {
      "slug": "policy-reach",
      "no": "12",
      "title": "政策直达快享，让红利免申即享"
    },
    {
      "slug": "hotline-efficiency",
      "no": "13",
      "title": "接诉即办，热线电话里的治理考卷"
    },
    {
      "slug": "public-data",
      "no": "14",
      "title": "公共数据授权运营，唤醒沉睡的资源"
    },
    {
      "slug": "approval-reform",
      "no": "15",
      "title": "极简审批，把方便留给办事人"
    },
    {
      "slug": "fair-competition",
      "no": "16",
      "title": "公平竞争审查，给市场立好规矩"
    },
    {
      "slug": "credit-regulation",
      "no": "17",
      "title": "信用监管，让守信者一路绿灯"
    },
    {
      "slug": "tax-service",
      "no": "18",
      "title": "便民办税，把申报表变薄把服务变厚"
    },
    {
      "slug": "government-purchase",
      "no": "19",
      "title": "政府购买服务，专业的事交给专业的人"
    },
    {
      "slug": "accessible-service",
      "no": "20",
      "title": "政务适老化，不让一位群众掉队"
    }
  ],
  "grassroots": [
    {
      "slug": "grassroots-governance",
      "no": "01",
      "title": "基层治理，关键是把“最后一公里”走成“最暖一公里”"
    },
    {
      "slug": "four-grassroots",
      "no": "02",
      "title": "“四下基层”，下的是基层，连的是民心"
    },
    {
      "slug": "fengqiao-experience",
      "no": "03",
      "title": "新时代“枫桥经验”，贵在矛盾不上交、服务不缺位"
    },
    {
      "slug": "liuchixiang-method",
      "no": "04",
      "title": "“六尺巷工作法”，让礼让有温度、调解有尺度"
    },
    {
      "slug": "four-governance",
      "no": "05",
      "title": "自治、法治、德治、智治，要各有其位更要协同发力"
    },
    {
      "slug": "grassroots-burden-reduction",
      "no": "06",
      "title": "基层减负，减的是无谓负担，增的是干事效能"
    },
    {
      "slug": "community-governance",
      "no": "07",
      "title": "社区治理，要在“家门口”把民生小事办好"
    },
    {
      "slug": "urban-governance",
      "no": "08",
      "title": "城市治理，要像绣花一样精细，也要像生命体一样协同"
    },
    {
      "slug": "smart-city",
      "no": "09",
      "title": "智慧城市，智慧不只在“屏”上更要在治理中"
    },
    {
      "slug": "refined-city-management",
      "no": "10",
      "title": "精细化治理，要从“差不多”走向“刚刚好”"
    },
    {
      "slug": "community-workers",
      "no": "11",
      "title": "社区工作者，小巷总理的职业春天"
    },
    {
      "slug": "property-governance",
      "no": "12",
      "title": "物业治理，小区里的民生大学问"
    },
    {
      "slug": "grid-governance",
      "no": "13",
      "title": "多网合一，网格里的治理绣花功"
    },
    {
      "slug": "emergency-grassroots",
      "no": "14",
      "title": "基层应急，把防线筑在第一线"
    },
    {
      "slug": "old-community-renewal",
      "no": "15",
      "title": "老旧小区改造，把民生工程改到心坎上"
    },
    {
      "slug": "dispute-mediation",
      "no": "16",
      "title": "多元解纷，把矛盾化解在诉前"
    },
    {
      "slug": "community-business",
      "no": "17",
      "title": "一刻钟生活圈，把便利画在步行可达处"
    },
    {
      "slug": "new-citizens",
      "no": "18",
      "title": "新市民融入，让此心安处是吾乡"
    },
    {
      "slug": "smart-community",
      "no": "19",
      "title": "智慧社区，数字赋能不添负担"
    },
    {
      "slug": "electric-bike-governance",
      "no": "20",
      "title": "电动自行车治理，堵与疏的平衡术"
    }
  ],
  "enforcement": [
    {
      "slug": "rule-of-law",
      "no": "01",
      "title": "全面依法治国，让法治成为发展最可靠的制度保障"
    },
    {
      "slug": "scientific-legislation",
      "no": "02",
      "title": "科学立法，要让法律立得住、行得通、真管用"
    },
    {
      "slug": "strict-enforcement",
      "no": "03",
      "title": "严格执法，严的是违法行为，守的是公平秩序"
    },
    {
      "slug": "fair-justice",
      "no": "04",
      "title": "公正司法，让公平正义以看得见的方式实现"
    },
    {
      "slug": "law-abiding-society",
      "no": "05",
      "title": "全民守法，让法治从“纸面规则”成为“生活习惯”"
    },
    {
      "slug": "people-centered-enforcement",
      "no": "06",
      "title": "执法为民，既要维护秩序也要守护民生"
    },
    {
      "slug": "flexible-enforcement",
      "no": "07",
      "title": "柔性执法，柔的是方式，不是法律底线"
    },
    {
      "slug": "service-oriented-enforcement",
      "no": "08",
      "title": "服务型执法，服务不是放松监管而是促进守法"
    },
    {
      "slug": "smart-enforcement",
      "no": "09",
      "title": "智慧执法，技术可以提效但不能代替判断"
    },
    {
      "slug": "enforcement-supervision",
      "no": "10",
      "title": "执法监督，要让权力每一次出手都有边界"
    },
    {
      "slug": "enforcement-team",
      "no": "11",
      "title": "高素质执法队伍，既要懂法律也要懂群众"
    },
    {
      "slug": "administrative-punishment-law",
      "no": "12",
      "title": "行政处罚，过罚相当方能服人"
    },
    {
      "slug": "comprehensive-law-enforcement",
      "no": "13",
      "title": "综合行政执法，一支队伍管到底"
    },
    {
      "slug": "cross-domain-enforcement",
      "no": "14",
      "title": "跨部门联合执法，进一次门查多项事"
    },
    {
      "slug": "enforcement-standard",
      "no": "15",
      "title": "执法规范化，把权力关进制度的笼子"
    },
    {
      "slug": "administrative-reconsideration",
      "no": "16",
      "title": "行政复议，化解民告官的主渠道"
    },
    {
      "slug": "public-interest-litigation",
      "no": "17",
      "title": "公益诉讼，为公共利益撑腰"
    },
    {
      "slug": "law-popularization",
      "no": "18",
      "title": "全民普法，让法治成为全民信仰"
    },
    {
      "slug": "business-law-protection",
      "no": "19",
      "title": "规范涉企执法，为企业撑起法治晴空"
    },
    {
      "slug": "administrative-litigation",
      "no": "20",
      "title": "负责人出庭，官司桌前见真章"
    }
  ],
  "rural": [
    {
      "slug": "rural-revitalization",
      "no": "01",
      "title": "乡村振兴，振的是产业更是乡村整体活力"
    },
    {
      "slug": "thousand-villages-project",
      "no": "02",
      "title": "读懂“千万工程”，不能只学环境整治的表面"
    },
    {
      "slug": "food-security",
      "no": "03",
      "title": "粮食安全这根弦，丰年也不能松"
    },
    {
      "slug": "harmonious-villages",
      "no": "04",
      "title": "建设和美乡村，既要村容整洁也要人心和顺"
    },
    {
      "slug": "rural-living-environment",
      "no": "05",
      "title": "农村人居环境整治，难在长效不在一次动员"
    },
    {
      "slug": "rural-industry-integration",
      "no": "06",
      "title": "发展乡村产业，要种得好也要卖得好"
    },
    {
      "slug": "rural-talent",
      "no": "07",
      "title": "乡村振兴的关键在人，难点也在人"
    },
    {
      "slug": "rural-culture-revitalization",
      "no": "08",
      "title": "乡村文化振兴，要留住乡愁也要接上时代"
    },
    {
      "slug": "consolidate-poverty-alleviation",
      "no": "09",
      "title": "巩固脱贫成果，防返贫比促增收更需要紧盯"
    },
    {
      "slug": "new-agricultural-entities",
      "no": "10",
      "title": "培育新型农业经营主体，要把小农户带进现代农业"
    },
    {
      "slug": "seed-industry",
      "no": "11",
      "title": "种业振兴，把中国饭碗端得更牢"
    },
    {
      "slug": "arable-land",
      "no": "12",
      "title": "耕地保护，红线之下寸土必珍"
    },
    {
      "slug": "county-rural-integration",
      "no": "13",
      "title": "城乡融合，让要素双向流动起来"
    },
    {
      "slug": "digital-countryside",
      "no": "14",
      "title": "数字乡村，一根网线连起山内外"
    },
    {
      "slug": "rural-infrastructure",
      "no": "15",
      "title": "四好农村路，铺就乡村振兴的康庄道"
    },
    {
      "slug": "collective-economy",
      "no": "16",
      "title": "集体经济，村集体要有活钱办事"
    },
    {
      "slug": "rural-finance",
      "no": "17",
      "title": "农村金融，活水浇灌希望的田野"
    },
    {
      "slug": "rural-elderly",
      "no": "18",
      "title": "农村养老，互助幸福院里的夕阳红"
    },
    {
      "slug": "rural-medical",
      "no": "19",
      "title": "县域医共体，看病不再翻山越岭"
    },
    {
      "slug": "big-food-concept",
      "no": "20",
      "title": "大食物观，饭碗里的多元交响"
    }
  ]
} as const satisfies Record<string, readonly WritingLeafIndexItem[]>;

export const caseLeafIndex = {
  "people": [
    {
      "slug": "huang-wenxiu",
      "no": "01",
      "title": "黄文秀：把青春扎进基层一线"
    },
    {
      "slug": "zhang-guimei",
      "no": "02",
      "title": "张桂梅：把一件平凡的事长期做下去"
    },
    {
      "slug": "fan-jinshi",
      "no": "03",
      "title": "樊锦诗：把一生交给敦煌"
    },
    {
      "slug": "jiao-yulu",
      "no": "04",
      "title": "焦裕禄：在风沙地里找办法而不是找理由"
    },
    {
      "slug": "kong-fansen",
      "no": "05",
      "title": "孔繁森：两次进藏，把脚印留在最偏远的地方"
    },
    {
      "slug": "wang-jinxi",
      "no": "06",
      "title": "王进喜：“铁人”的底气来自吃过的苦"
    },
    {
      "slug": "yang-shanzhou",
      "no": "07",
      "title": "杨善洲：退休后的二十二年在山上"
    },
    {
      "slug": "wang-jicai",
      "no": "08",
      "title": "王继才：开山岛上的三十二年"
    },
    {
      "slug": "li-baoguo",
      "no": "09",
      "title": "李保国：太行山上的“新愚公”"
    },
    {
      "slug": "zhang-fuqing",
      "no": "10",
      "title": "张富清：把功名锁进箱底六十多年"
    },
    {
      "slug": "shen-hao",
      "no": "11",
      "title": "沈浩：小岗村里两次被按下的红手印"
    },
    {
      "slug": "du-fuguo",
      "no": "12",
      "title": "杜富国：“你退后，让我来”"
    },
    {
      "slug": "laqini-bayika",
      "no": "13",
      "title": "拉齐尼·巴依卡：帕米尔高原上的三代护边"
    },
    {
      "slug": "yuan-longping",
      "no": "14",
      "title": "袁隆平：把论文写在稻田里"
    },
    {
      "slug": "tu-youyou",
      "no": "15",
      "title": "屠呦呦：从传统典籍中找到现代科学线索"
    },
    {
      "slug": "nan-rendong",
      "no": "16",
      "title": "南仁东：为“中国天眼”守住二十多年的目标"
    },
    {
      "slug": "huang-danian",
      "no": "17",
      "title": "黄大年：把个人选择放进国家需要"
    },
    {
      "slug": "zhong-yang",
      "no": "18",
      "title": "钟扬：把种子和知识留给未来"
    },
    {
      "slug": "qian-qihu",
      "no": "19",
      "title": "钱七虎：把一生研究放在国家安全底座上"
    },
    {
      "slug": "deng-qingming",
      "no": "20",
      "title": "邓清明：二十余年备份，不把“没有上场”当作放弃理由"
    }
  ],
  "practice": [
    {
      "slug": "qianwan-project",
      "no": "01",
      "title": "“千万工程”：一张蓝图为什么能画二十多年"
    },
    {
      "slug": "fengqiao-experience",
      "no": "02",
      "title": "“枫桥经验”：把矛盾化解在离群众最近的地方"
    },
    {
      "slug": "liuchixiang-method",
      "no": "03",
      "title": "“六尺巷工作法”：让传统礼让进入基层治理"
    },
    {
      "slug": "huikyou-huitian",
      "no": "04",
      "title": "北京“回天有我”：超大型社区唤醒沉睡的居民"
    },
    {
      "slug": "shanghai-yiwangtongguan-shequ",
      "no": "05",
      "title": "上海“一网统管”：把城市当成一台机器来照看"
    },
    {
      "slug": "beijing-xiaoxiangguanjia",
      "no": "06",
      "title": "北京“小巷管家”：把背街小巷交给走得到的人"
    },
    {
      "slug": "chongqing-laoma-studio",
      "no": "07",
      "title": "重庆“老马工作室”：调解是一门可以传授的手艺"
    },
    {
      "slug": "pudong-homefront-service",
      "no": "08",
      "title": "上海浦东“家门口”服务体系：把服务站开到楼组门口"
    },
    {
      "slug": "hangzhou-minhu-wo-wei",
      "no": "09",
      "title": "杭州“民呼我为”：把民意数据变成任务清单"
    },
    {
      "slug": "shenzhen-minsheng-weishishi",
      "no": "10",
      "title": "深圳福田“民生微实事”：小额资金快速办身边事"
    },
    {
      "slug": "hubei-gongtong-dizao",
      "no": "11",
      "title": "“共同缔造”：从“要我干”到“一起干”的方法论"
    },
    {
      "slug": "chengdu-xintuo-wuye",
      "no": "12",
      "title": "成都“信托制物业”：把物业费花在阳光下"
    },
    {
      "slug": "jinjiang-experience",
      "no": "13",
      "title": "“晋江经验”：实体经济是熬出来的"
    },
    {
      "slug": "pujiang-experience",
      "no": "14",
      "title": "“浦江经验”：领导干部下访，把矛盾解决在一线"
    },
    {
      "slug": "courtyard-council",
      "no": "15",
      "title": "“小院议事厅”：居民的事让居民坐下来商量"
    },
    {
      "slug": "whistle-report-departments",
      "no": "16",
      "title": "“街乡吹哨、部门报到”：基层发现问题，专业力量协同解决"
    },
    {
      "slug": "villager-discussion",
      "no": "17",
      "title": "“村民说事”：把乡村公共事务摆到桌面上"
    },
    {
      "slug": "points-based-governance",
      "no": "18",
      "title": "积分制治理：把文明乡风从口号变成日常行动"
    },
    {
      "slug": "five-social-linkage",
      "no": "19",
      "title": "“五社联动”：社区不再只靠社区干部单打独斗"
    },
    {
      "slug": "micro-grid-governance",
      "no": "20",
      "title": "微网格治理：把治理触角延伸到楼栋和村组"
    }
  ],
  "city": [
    {
      "slug": "jingdezhen-taoxichuan",
      "no": "01",
      "title": "景德镇陶溪川：老厂房如何长出新业态"
    },
    {
      "slug": "shanghai-15min-life-circle",
      "no": "02",
      "title": "上海“15分钟社区生活圈”：把城市尺度落到人的脚步"
    },
    {
      "slug": "chengdu-park-city",
      "no": "03",
      "title": "成都公园城市：把生态空间嵌入城市生活"
    },
    {
      "slug": "beijing-shougang-park",
      "no": "04",
      "title": "北京首钢园：百年钢厂的长冬与长红"
    },
    {
      "slug": "shanghai-yangpu-riverside",
      "no": "05",
      "title": "上海杨浦滨江：从“工业锈带”到“生活秀带”"
    },
    {
      "slug": "zibo-barbecue",
      "no": "06",
      "title": "淄博烧烤：一座城市接住流量的全流程"
    },
    {
      "slug": "harbin-ice-snow",
      "no": "07",
      "title": "哈尔滨冰雪季：把“尔滨”式宠客变成服务标准"
    },
    {
      "slug": "hangzhou-crosswalk-yield",
      "no": "08",
      "title": "杭州“礼让斑马线”：一条线上的城市文明刻度"
    },
    {
      "slug": "wuhan-riverside-park",
      "no": "09",
      "title": "武汉江滩：把生产岸线还给市民"
    },
    {
      "slug": "xian-datang-city",
      "no": "10",
      "title": "西安大唐不夜城：文化IP如何撑起一条街"
    },
    {
      "slug": "xiongan-digital-twin",
      "no": "11",
      "title": "雄安新区：先把数字城市与物理城市一起建"
    },
    {
      "slug": "nanjing-xiaoxihu",
      "no": "12",
      "title": "南京小西湖：老街区改造先问“去与留”"
    },
    {
      "slug": "shanghai-buildings-readable",
      "no": "13",
      "title": "上海“建筑可阅读”：给老房子一块会说故事的牌子"
    },
    {
      "slug": "hangzhou-city-brain",
      "no": "14",
      "title": "杭州“城市大脑”：技术要进入真实城市问题"
    },
    {
      "slug": "suzhou-old-city-renewal",
      "no": "15",
      "title": "苏州古城保护：更新城市，也保留生活的纹理"
    },
    {
      "slug": "guangzhou-yongqingfang",
      "no": "16",
      "title": "广州永庆坊：老街区用“微改造”连接新生活"
    },
    {
      "slug": "chongqing-mountain-trails",
      "no": "17",
      "title": "重庆山城步道：把“边角空间”变成公共生活空间"
    },
    {
      "slug": "shenzhen-child-friendly",
      "no": "18",
      "title": "深圳儿童友好城市：用“一米高度”重新看城市"
    },
    {
      "slug": "fuzhou-water-system",
      "no": "19",
      "title": "福州水系治理：治一条河，也要治一座城的系统"
    },
    {
      "slug": "beijing-pocket-parks",
      "no": "20",
      "title": "北京口袋公园：城市品质也藏在家门口的“小空间”"
    }
  ],
  "rural": [
    {
      "slug": "yucun-two-mountains",
      "no": "01",
      "title": "浙江余村：从“卖石头”到“卖风景”"
    },
    {
      "slug": "xiadang-rural",
      "no": "02",
      "title": "福建下党乡：越是基础薄弱，越要从小事做起"
    },
    {
      "slug": "yuanjiacun",
      "no": "03",
      "title": "袁家村：一个村集体的“合伙人制度”"
    },
    {
      "slug": "zhanqi-village",
      "no": "04",
      "title": "成都战旗村：改革政策攒出的“土地账”"
    },
    {
      "slug": "rongjiang-village-super-league",
      "no": "05",
      "title": "贵州“村超”：土味足球如何踢出县域流量"
    },
    {
      "slug": "taipan-village-basketball",
      "no": "06",
      "title": "贵州“村BA”：一个篮球场带热一座苗岭小城"
    },
    {
      "slug": "wuyuan-huangling",
      "no": "07",
      "title": "婺源篁岭：把整村“搬”下山的旅游实验"
    },
    {
      "slug": "dailan-village-linyi",
      "no": "08",
      "title": "兰陵代村：一个负债村蹚出的共富路"
    },
    {
      "slug": "minning-town",
      "no": "09",
      "title": "闽宁镇：东西部协作写进大地的移民史"
    },
    {
      "slug": "deqing-digital-village",
      "no": "10",
      "title": "德清数字乡村：县域先把数据底座铺进村"
    },
    {
      "slug": "lianzhang-village",
      "no": "11",
      "title": "连樟村：破解“班子弱、产业散”两道题"
    },
    {
      "slug": "hani-terrace",
      "no": "12",
      "title": "哈尼梯田：种了千年的“活态遗产”如何分红"
    },
    {
      "slug": "shibadong-village",
      "no": "13",
      "title": "十八洞村：精准帮扶先从“这个村真正缺什么”问起"
    },
    {
      "slug": "shouguang-vegetables",
      "no": "14",
      "title": "寿光蔬菜：一棵菜背后是技术、市场和物流体系"
    },
    {
      "slug": "anji-white-tea",
      "no": "15",
      "title": "安吉白茶：“一片叶子”如何连接生态和富民产业"
    },
    {
      "slug": "liuzhou-luosifen",
      "no": "16",
      "title": "柳州螺蛳粉：地方小吃也能带动一条产业链"
    },
    {
      "slug": "shaxian-snacks",
      "no": "17",
      "title": "沙县小吃：小餐饮背后的创业服务网络"
    },
    {
      "slug": "caoxian-ecommerce",
      "no": "18",
      "title": "曹县电商：数字平台怎样连接县域制造和全国市场"
    },
    {
      "slug": "xiajiang-village",
      "no": "19",
      "title": "浙江下姜村：从单村发展走向片区共同发展"
    },
    {
      "slug": "gutian-edible-fungi",
      "no": "20",
      "title": "古田食用菌：特色农业也要靠科技和标准升级"
    }
  ],
  "livelihood": [
    {
      "slug": "community-canteen",
      "no": "01",
      "title": "社区食堂：一顿饭里的公共服务温度"
    },
    {
      "slug": "courier-friendly-community",
      "no": "02",
      "title": "骑手友好社区：让公共服务跟着新职业变化"
    },
    {
      "slug": "youth-night-school",
      "no": "03",
      "title": "青年夜校：公共文化也要跟上年轻人的作息"
    },
    {
      "slug": "after-school-430",
      "no": "04",
      "title": "“四点半课堂”：放学后的两小时交给谁"
    },
    {
      "slug": "workers-rest-station",
      "no": "05",
      "title": "工会驿站：给户外劳动者一个落脚点"
    },
    {
      "slug": "elevator-installation",
      "no": "06",
      "title": "老楼加装电梯：三分之二同意之外的功夫"
    },
    {
      "slug": "shared-parking-offpeak",
      "no": "07",
      "title": "错峰共享停车：让白天的车位等晚上的人"
    },
    {
      "slug": "city-custom-insurance",
      "no": "08",
      "title": "“惠民保”：一年百元级保费如何兜住大病"
    },
    {
      "slug": "time-bank-eldercare",
      "no": "09",
      "title": "“时间银行”：把今天的照护存给明天"
    },
    {
      "slug": "summer-holiday-care",
      "no": "10",
      "title": "职工子女暑托班：假期看护不是一家一户的事"
    },
    {
      "slug": "night-outpatient-clinic",
      "no": "11",
      "title": "夜间门诊：让上班族的病看得上、孩子少请假"
    },
    {
      "slug": "breakfast-project",
      "no": "12",
      "title": "“早餐工程”：一份热豆浆背后的城市烟火"
    },
    {
      "slug": "community-fitness-corner",
      "no": "13",
      "title": "健身步道与运动角：把“十五分钟”还给身体"
    },
    {
      "slug": "family-doctor-contract",
      "no": "14",
      "title": "家庭医生：把健康服务从医院延伸到日常"
    },
    {
      "slug": "long-term-care-insurance",
      "no": "15",
      "title": "长期护理保险：给失能家庭多一层照护支撑"
    },
    {
      "slug": "home-care-bed",
      "no": "16",
      "title": "家庭养老床位：把专业照护服务送进家门"
    },
    {
      "slug": "inclusive-childcare",
      "no": "17",
      "title": "普惠托育：把年轻家庭最缺的时间补回来"
    },
    {
      "slug": "urban-study-room",
      "no": "18",
      "title": "城市书房：公共文化服务也可以“小而近”"
    },
    {
      "slug": "barrier-free-renovation",
      "no": "19",
      "title": "无障碍改造：一段坡道体现一座城市的文明尺度"
    },
    {
      "slug": "youth-station",
      "no": "20",
      "title": "青年驿站：给求职青年一段低成本“落脚期”"
    }
  ],
  "culture": [
    {
      "slug": "palace-museum-cultural",
      "no": "01",
      "title": "故宫文创：传统文化怎样走进日常"
    },
    {
      "slug": "quanzhou-living-heritage",
      "no": "02",
      "title": "泉州古城：遗产保护不是把城市冻住"
    },
    {
      "slug": "juexing-niandai",
      "no": "03",
      "title": "《觉醒年代》：主旋律如何成为青年的“电子榨菜”"
    },
    {
      "slug": "sanxingdui-new-museum",
      "no": "04",
      "title": "三星堆新馆：考古如何变成全民追更"
    },
    {
      "slug": "chang-an-sanwanli",
      "no": "05",
      "title": "《长安三万里》：课本里的诗人第一次让大人落泪"
    },
    {
      "slug": "digital-dunhuang",
      "no": "06",
      "title": "“数字敦煌”：让千年壁画被参观也少被打扰"
    },
    {
      "slug": "black-myth-wukong",
      "no": "07",
      "title": "《黑神话：悟空》：一只猴子闯出的文化出海新路"
    },
    {
      "slug": "new-chinese-style",
      "no": "08",
      "title": "“新中式”马面裙：从衣柜里的选择看文化认同"
    },
    {
      "slug": "xunpu-zanhua",
      "no": "09",
      "title": "蟳埔簪花围：一朵花盘活一个渔村"
    },
    {
      "slug": "village-gala",
      "no": "10",
      "title": "“村晚”：农民自办的晚会凭什么好看"
    },
    {
      "slug": "grand-canal-museum",
      "no": "11",
      "title": "扬州中国大运河博物馆：一条河的全体面世"
    },
    {
      "slug": "dianji-li-de-zhongguo",
      "no": "12",
      "title": "《典籍里的中国》：让古书主角走出故纸堆"
    },
    {
      "slug": "liangzhu-heritage",
      "no": "13",
      "title": "良渚古城遗址：让考古成果成为理解文明的入口"
    },
    {
      "slug": "beijing-central-axis",
      "no": "14",
      "title": "北京中轴线：保护的是建筑序列，也是城市历史秩序"
    },
    {
      "slug": "only-green-dance",
      "no": "15",
      "title": "《只此青绿》：传统审美如何转化成当代表达"
    },
    {
      "slug": "china-festival-series",
      "no": "16",
      "title": "“中国节日”节目：让传统节日进入年轻人的屏幕"
    },
    {
      "slug": "intangible-heritage-workshops",
      "no": "17",
      "title": "非遗工坊：让传承技艺也能创造就业和收入"
    },
    {
      "slug": "yin-ruins-museum",
      "no": "18",
      "title": "殷墟博物馆：把考古知识从“专业现场”带到公众面前"
    },
    {
      "slug": "xian-city-wall",
      "no": "19",
      "title": "西安城墙：历史遗产也可以成为日常公共文化空间"
    },
    {
      "slug": "ancient-books-digitization",
      "no": "20",
      "title": "古籍数字化：让珍贵典籍少翻一页，也能多被看见一次"
    }
  ],
  "ecology": [
    {
      "slug": "saihanba",
      "no": "01",
      "title": "塞罕坝：把荒原一代代种成林海"
    },
    {
      "slug": "yangtze-fishing-ban",
      "no": "02",
      "title": "长江十年禁渔：一条禁令背后的系统治理"
    },
    {
      "slug": "muwusu-desert",
      "no": "03",
      "title": "毛乌素沙地：从“沙进人退”到“绿进沙退”"
    },
    {
      "slug": "babusha-six-elders",
      "no": "04",
      "title": "八步沙“六老汉”：一份按了手印的治沙约定"
    },
    {
      "slug": "changting-soil-erosion",
      "no": "05",
      "title": "长汀水土流失治理：从“火焰山”到“花果山”"
    },
    {
      "slug": "baiyangdian-recovery",
      "no": "06",
      "title": "白洋淀：水质回升背后的补水与控源"
    },
    {
      "slug": "kekexili-tibetan-antelope",
      "no": "07",
      "title": "可可西里藏羚羊：从盗猎枪声到迁徙产房"
    },
    {
      "slug": "chongming-eco-island",
      "no": "08",
      "title": "崇明世界级生态岛：把“留白”作为战略"
    },
    {
      "slug": "tarim-populus",
      "no": "09",
      "title": "塔里木河生态输水：给胡杨林续上的一次次水"
    },
    {
      "slug": "xinan-river-compensation",
      "no": "10",
      "title": "新安江生态补偿：皖浙两省的“对赌”账本"
    },
    {
      "slug": "guangyang-island",
      "no": "11",
      "title": "重庆广阳岛：一个“半拉子开发”的生态转身"
    },
    {
      "slug": "taihu-governance",
      "no": "12",
      "title": "太湖治理：一场打了二十年的持久战"
    },
    {
      "slug": "kubuqi-desert-control",
      "no": "13",
      "title": "库布其治沙：生态治理是一场跨越很多年的接力"
    },
    {
      "slug": "sanjiangyuan-national-park",
      "no": "14",
      "title": "三江源国家公园：保护完整生态系统，而不是只保护几个景点"
    },
    {
      "slug": "shenzhen-mangrove",
      "no": "15",
      "title": "深圳红树林：城市越密集，越需要给自然留下空间"
    },
    {
      "slug": "erhai-lake-governance",
      "no": "16",
      "title": "洱海保护：治湖先治岸，治水也要治生产生活方式"
    },
    {
      "slug": "qinling-protection",
      "no": "17",
      "title": "秦岭生态保护：生态红线必须成为真正的硬约束"
    },
    {
      "slug": "yellow-river-delta-wetland",
      "no": "18",
      "title": "黄河三角洲湿地：生态修复要给候鸟和自然过程留空间"
    },
    {
      "slug": "ningxia-straw-checkerboard",
      "no": "19",
      "title": "麦草方格治沙：小办法背后是对自然规律的理解"
    },
    {
      "slug": "chishui-river-protection",
      "no": "20",
      "title": "赤水河保护：一条河需要上下游一起守"
    }
  ],
  "technology": [
    {
      "slug": "beidou-application",
      "no": "01",
      "title": "北斗规模应用：技术突破还要走完“最后一公里”"
    },
    {
      "slug": "shenzhen-low-altitude",
      "no": "02",
      "title": "深圳低空配送：新产业先从真实场景起飞"
    },
    {
      "slug": "c919-industry",
      "no": "03",
      "title": "C919：一架大飞机背后的系统创新"
    },
    {
      "slug": "micius-satellite",
      "no": "04",
      "title": "“墨子号”：量子通信从纸面到星地"
    },
    {
      "slug": "jiuzhang-quantum",
      "no": "05",
      "title": "“九章”：中国光量子计算的原型验证"
    },
    {
      "slug": "baihetan-hydropower",
      "no": "06",
      "title": "白鹤滩水电站：世界级工程的“中国精度”"
    },
    {
      "slug": "hzm-bridge",
      "no": "07",
      "title": "港珠澳大桥：五十五公里背后的每一毫米"
    },
    {
      "slug": "shenzhong-link",
      "no": "08",
      "title": "深中通道：伶仃洋上再下一城"
    },
    {
      "slug": "aida-cruise",
      "no": "09",
      "title": "“爱达·魔都号”：国产大型邮轮的下水课"
    },
    {
      "slug": "hualong-prime",
      "no": "10",
      "title": "“华龙一号”：给中国核电装上自己的脑子"
    },
    {
      "slug": "deep-sea-number-one",
      "no": "11",
      "title": "“深海一号”：把油气工厂搬到千米海底"
    },
    {
      "slug": "sunway-taihulight",
      "no": "12",
      "title": "神威·太湖之光：超算登顶之后的冷静"
    },
    {
      "slug": "domestic-llm-open-source",
      "no": "13",
      "title": "国产开源大模型：低成本路线的弯道突围"
    },
    {
      "slug": "change-lunar-project",
      "no": "14",
      "title": "嫦娥探月：重大科技工程是一场系统接力"
    },
    {
      "slug": "tianwen-mars",
      "no": "15",
      "title": "“天问一号”：把探索未知变成可执行的工程任务"
    },
    {
      "slug": "china-space-station",
      "no": "16",
      "title": "中国空间站：把重大工程变成开放的科研平台"
    },
    {
      "slug": "fuxing-highspeed",
      "no": "17",
      "title": "复兴号高铁：自主创新也来自庞大系统的协同升级"
    },
    {
      "slug": "fendouzhe-deepsea",
      "no": "18",
      "title": "“奋斗者”号：向深海要答案，先把关键技术做扎实"
    },
    {
      "slug": "5g-scale-application",
      "no": "19",
      "title": "5G规模应用：新技术要进入工厂、港口和真实生活"
    },
    {
      "slug": "east-data-west-computing",
      "no": "20",
      "title": "“东数西算”：算力布局也要算资源账和协同账"
    }
  ],
  "enterprise": [
    {
      "slug": "haier-industrial-internet",
      "no": "01",
      "title": "海尔工业互联网：传统制造也能长出新动能"
    },
    {
      "slug": "catl-innovation",
      "no": "02",
      "title": "宁德时代：越是热门赛道，越要靠研发站稳"
    },
    {
      "slug": "boe-counter-cyclical",
      "no": "03",
      "title": "京东方：逆周期下注面板的“冷板凳”"
    },
    {
      "slug": "transsion-africa",
      "no": "04",
      "title": "传音控股：把“下沉市场”做到另一个大洲"
    },
    {
      "slug": "anta-rd-ma",
      "no": "05",
      "title": "安踏：从代工到收购与自研并进"
    },
    {
      "slug": "weichai-efficiency",
      "no": "06",
      "title": "潍柴动力：把发动机热效率提高一个点"
    },
    {
      "slug": "xcmg-hanyun",
      "no": "07",
      "title": "徐工集团：工程机械的“数字外挂”"
    },
    {
      "slug": "beigene-brukinsa",
      "no": "08",
      "title": "百济神州：一粒药出海的漫长审批路"
    },
    {
      "slug": "ymtc-memory",
      "no": "09",
      "title": "长江存储：存储芯片的“后来者”身位"
    },
    {
      "slug": "mixue-supply-chain",
      "no": "10",
      "title": "蜜雪冰城：把一杯柠檬水做成了供应链生意"
    },
    {
      "slug": "pop-mart-ip",
      "no": "11",
      "title": "泡泡玛特：情绪价值的全球化生意"
    },
    {
      "slug": "jakarta-hsr",
      "no": "12",
      "title": "雅万高铁：中国高铁的第一次整体出海"
    },
    {
      "slug": "huawei-longterm-rd",
      "no": "13",
      "title": "华为研发投入：企业创新不能只算眼前利润账"
    },
    {
      "slug": "byd-new-energy",
      "no": "14",
      "title": "比亚迪新能源转型：技术路线要靠长期研发和市场检验"
    },
    {
      "slug": "dji-drones",
      "no": "15",
      "title": "大疆无人机：把核心技术做深，再把场景做宽"
    },
    {
      "slug": "midea-smart-manufacturing",
      "no": "16",
      "title": "美的智能制造：传统制造也能长出“数字新能力”"
    },
    {
      "slug": "fuyao-glass",
      "no": "17",
      "title": "福耀玻璃：在一个细分行业把质量和技术做深"
    },
    {
      "slug": "geely-rd",
      "no": "18",
      "title": "吉利汽车：从制造产品走向积累研发平台能力"
    },
    {
      "slug": "sany-smart-factory",
      "no": "19",
      "title": "三一重工智能工厂：工程机械也要从“制造”走向“智造”"
    },
    {
      "slug": "longi-photovoltaic",
      "no": "20",
      "title": "隆基绿能：光伏产业竞争最终要回到技术和成本"
    }
  ],
  "reform": [
    {
      "slug": "zhejiang-most-one-trip",
      "no": "01",
      "title": "浙江“最多跑一次”：让群众少跑腿，让部门多协同"
    },
    {
      "slug": "beijing-call-response",
      "no": "02",
      "title": "北京“接诉即办”：从解决一件事到治理一类事"
    },
    {
      "slug": "shanghai-one-network",
      "no": "03",
      "title": "上海“一网通办”：数字化先改流程，再改入口"
    },
    {
      "slug": "certificate-license-separation",
      "no": "04",
      "title": "“证照分离”：先照后证改了什么"
    },
    {
      "slug": "double-random-check",
      "no": "05",
      "title": "“双随机、一公开”：让检查不再看人下菜"
    },
    {
      "slug": "efficient-one-thing",
      "no": "06",
      "title": "“高效办成一件事”：国务院文件里的“一件事”"
    },
    {
      "slug": "business-env-pilot-cities",
      "no": "07",
      "title": "营商环境创新试点：六城市的授权实验"
    },
    {
      "slug": "no-application-benefits",
      "no": "08",
      "title": "“免申即享”：让政策主动找到企业"
    },
    {
      "slug": "construction-approval-reform",
      "no": "09",
      "title": "工程审批改革：从两百天到几十天"
    },
    {
      "slug": "power-access-three-zero",
      "no": "10",
      "title": "“三零”服务：小微企业办电不花一分冤枉钱"
    },
    {
      "slug": "contactless-tax",
      "no": "11",
      "title": "“非接触式”办税：留抵退税直达账上"
    },
    {
      "slug": "no-certificate-province",
      "no": "12",
      "title": "山东“无证明之省”：让证明的去证明"
    },
    {
      "slug": "hotline-12345-integration",
      "no": "13",
      "title": "12345热线整合：让“找不到门”变成“一号响应”"
    },
    {
      "slug": "cross-province-services",
      "no": "14",
      "title": "“跨省通办”：让群众流动，服务也跟着流动"
    },
    {
      "slug": "one-license-one-industry",
      "no": "15",
      "title": "“一业一证”：把多张许可从部门视角重新组合"
    },
    {
      "slug": "certificate-free-services",
      "no": "16",
      "title": "“免证办”：让数据多跑路，群众少找证明"
    },
    {
      "slug": "comprehensive-inspection-once",
      "no": "17",
      "title": "“综合查一次”：监管不能让企业反复迎检"
    },
    {
      "slug": "policy-direct-access",
      "no": "18",
      "title": "政策“直达快享”：好政策不能卡在“不会找、不知道”"
    },
    {
      "slug": "government-service-rating",
      "no": "19",
      "title": "政务服务“好差评”：把评价权交给办事群众"
    },
    {
      "slug": "birth-one-thing",
      "no": "20",
      "title": "“出生一件事”：围绕人生节点重组公共服务"
    }
  ],
  "law": [
    {
      "slug": "first-violation-no-penalty",
      "no": "01",
      "title": "“首违不罚”：柔性不是放松，关键是过罚相当"
    },
    {
      "slug": "offsite-supervision",
      "no": "02",
      "title": "非现场监管：技术提效不能替代程序判断"
    },
    {
      "slug": "reasoning-enforcement",
      "no": "03",
      "title": "说理式执法：把法理讲清，也把整改路径讲明"
    },
    {
      "slug": "civil-code-enactment",
      "no": "04",
      "title": "民法典：社会生活的百科全书落地"
    },
    {
      "slug": "who-enforces-who-popularizes",
      "no": "05",
      "title": "“谁执法谁普法”：普法从普法办的事变成大家的事"
    },
    {
      "slug": "administrative-reconsideration-reform",
      "no": "06",
      "title": "行政复议体制改革：化解“官民”纠纷的主渠道"
    },
    {
      "slug": "yangtze-river-protection-law",
      "no": "07",
      "title": "长江保护法：为一条河立一部法"
    },
    {
      "slug": "personal-information-law",
      "no": "08",
      "title": "个人信息保护法：数字时代的“守门法条”"
    },
    {
      "slug": "anti-food-waste-law",
      "no": "09",
      "title": "反食品浪费法：把“光盘”写进法条"
    },
    {
      "slug": "iron-fist-action",
      "no": "10",
      "title": "“铁拳”行动：民生领域执法的年度清单"
    },
    {
      "slug": "barrier-free-law",
      "no": "11",
      "title": "无障碍环境建设法：一部法律拓宽的通行空间"
    },
    {
      "slug": "daily-penalty-epi",
      "no": "12",
      "title": "按日计罚：环保法长出的“牙齿”"
    },
    {
      "slug": "sunken-plate-village",
      "no": "13",
      "title": "“公开听证”：让争议案件晒在阳光下裁断"
    },
    {
      "slug": "administrative-discretion-benchmark",
      "no": "14",
      "title": "行政裁量基准：让“同案不同罚”少一点"
    },
    {
      "slug": "full-process-enforcement-recording",
      "no": "15",
      "title": "执法全过程记录：让权力运行留下必要轨迹"
    },
    {
      "slug": "major-enforcement-legal-review",
      "no": "16",
      "title": "重大执法决定法制审核：重要决定先过一道“法治闸门”"
    },
    {
      "slug": "enforcement-publicity",
      "no": "17",
      "title": "行政执法公示：让检查和处罚先把规则讲明白"
    },
    {
      "slug": "compliance-guidance",
      "no": "18",
      "title": "合规指导：把执法从“发现问题”延伸到“帮助改好”"
    },
    {
      "slug": "public-legal-service",
      "no": "19",
      "title": "公共法律服务：让群众遇事有地方问法、用法"
    },
    {
      "slug": "public-interest-litigation",
      "no": "20",
      "title": "公益诉讼：为分散的公共利益增加一道法治守护"
    }
  ],
  "negative": [
    {
      "slug": "repeated-forms",
      "no": "01",
      "title": "重复填表留痕：基层时间为何耗在“证明自己干过”"
    },
    {
      "slug": "one-size-fits-all-governance",
      "no": "02",
      "title": "“一刀切”治理：看似省事，实则增加治理成本"
    },
    {
      "slug": "digital-formalism",
      "no": "03",
      "title": "“指尖上的形式主义”：工具为什么反而成了负担"
    },
    {
      "slug": "small-horse-big-cart",
      "no": "04",
      "title": "“小马拉大车”：基层权责失衡的典型症候"
    },
    {
      "slug": "check-in-sinking",
      "no": "05",
      "title": "“打卡式”下沉：干部下去了，问题没上来"
    },
    {
      "slug": "bonsai-investigation",
      "no": "06",
      "title": "“盆景式”调研：被布置好的真实"
    },
    {
      "slug": "zombie-government-accounts",
      "no": "07",
      "title": "政务新媒体“僵尸号”：开了不更、更了不答"
    },
    {
      "slug": "price-assassin-passive-regulation",
      "no": "08",
      "title": "“价格刺客”事件：为什么总要等舆情来执法"
    },
    {
      "slug": "whitewashed-walls",
      "no": "09",
      "title": "“刷白墙”：把民生工程刷成了“面子工程”"
    },
    {
      "slug": "emergency-greening",
      "no": "10",
      "title": "突击复绿：应付督察的“连夜施工”"
    },
    {
      "slug": "inspection-driven-cleanup",
      "no": "11",
      "title": "“迎检式”整治：检查一走，问题回潮"
    },
    {
      "slug": "report-material-achievements",
      "no": "12",
      "title": "“材料政绩”：PPT里的乡村振兴"
    },
    {
      "slug": "responsibility-dumping",
      "no": "13",
      "title": "属地管理变“责任甩锅”：板子总打在最基层"
    },
    {
      "slug": "vanity-project-warning",
      "no": "14",
      "title": "形象工程：看起来“有政绩”，为什么可能留下真负担"
    },
    {
      "slug": "repeated-enterprise-inspections",
      "no": "15",
      "title": "多头重复检查：监管为什么会变成企业负担"
    },
    {
      "slug": "excessive-landscaping",
      "no": "16",
      "title": "过度景观化：乡村建设不能把生活空间做成“样板间”"
    },
    {
      "slug": "campaign-style-closure",
      "no": "17",
      "title": "运动式“一关了之”：治理不能把复杂问题只剩一个按钮"
    },
    {
      "slug": "data-beautification",
      "no": "18",
      "title": "数据“美颜”：数字好看不等于工作真的变好"
    },
    {
      "slug": "layered-additional-requirements",
      "no": "19",
      "title": "层层加码：为什么越到基层任务反而越“变形”"
    },
    {
      "slug": "meeting-document-formalism",
      "no": "20",
      "title": "以会议落实会议：忙碌为什么可能没有产出"
    }
  ]
} as const satisfies Record<string, readonly WritingLeafIndexItem[]>;
