import type { LearningRouteKey } from './learning-routes';

export type LearningReadingGuideEntry = Readonly<{
  route: LearningRouteKey;
  chapterId: string;
  chapterNo: string;
  chapterLabel: string;
  points: readonly [string, string, string];
  exercise: string;
}>;

export const learningReadingGuides = [
  {
    route: 'shenlun-framework',
    chapterId: 'framework-expression',
    chapterNo: '01',
    chapterLabel: '表达规则',
    points: ['认识考试与答题卡限制', '先审清题干任务', '把材料信息转成答案语言'],
    exercise: '选一道小题，圈出任务、对象和字数，再写出三条材料要点。',
  },
  {
    route: 'shenlun-framework',
    chapterId: 'framework-types',
    chapterNo: '02',
    chapterLabel: '题型框架',
    points: ['判断题目要找什么', '区分要素题和理解题', '按题型选择答案结构'],
    exercise: '拿五道旧题，只标注题型、作答任务和应使用的结构顺序。',
  },
  {
    route: 'shenlun-framework',
    chapterId: 'framework-abilities',
    chapterNo: '03',
    chapterLabel: '核心能力',
    points: ['拆开材料里的关系', '合并同类要点', '用有限字数准确表达'],
    exercise: '从一段材料中提取五个要点，合并成两组并各写一句概括。',
  },
  {
    route: 'shenlun-framework',
    chapterId: 'framework-tips',
    chapterNo: '04',
    chapterLabel: '实用技巧',
    points: ['定位做题卡点', '按问题选择短文阅读', '读完立刻回到题目验证'],
    exercise: '挑一篇与你当前错误相关的短文，改写上一道题中最弱的一段。',
  },
  {
    route: 'shenlun-questions',
    chapterId: 'questions-years',
    chapterNo: '01',
    chapterLabel: '按年份看',
    points: ['连续观察整卷主题', '体会题型组合节奏', '保留同套题复盘线索'],
    exercise: '选一年真题，按题号写下主题、题型和每题建议用时。',
  },
  {
    route: 'shenlun-questions',
    chapterId: 'questions-types',
    chapterNo: '02',
    chapterLabel: '按题型练',
    points: ['五大题型交叉训练', '对照不同题型任务', '补齐短板题型动作'],
    exercise: '同一题型连做三题，每题只记录审题关键词和失分点。',
  },
  {
    route: 'shenlun-questions',
    chapterId: 'questions-themes',
    chapterNo: '03',
    chapterLabel: '按主题复盘',
    points: ['把相近主题放在一起', '比较材料表达变化', '观察命题角度差异'],
    exercise: '找两道同主题题目，分别写出材料共同点和命题差别。',
  },
  {
    route: 'shenlun-questions',
    chapterId: 'questions-index',
    chapterNo: '04',
    chapterLabel: '真题索引',
    points: ['先看任务和训练重点', '按建议时间完成作答', '对照参考方向复盘'],
    exercise: '完成索引中一道题，写下答案依据、遗漏要点和下一次修改动作。',
  },
  {
    route: 'shenlun-writing',
    chapterId: 'writing-hotspots',
    chapterNo: '01',
    chapterLabel: '热点时评',
    points: ['按知识领域读文章', '练习立观点和选论据', '拆解文章论证结构'],
    exercise: '选一篇热点文章，摘出中心论点、两个论据和一处可迁移表达。',
  },
  {
    route: 'shenlun-writing',
    chapterId: 'writing-cases',
    chapterNo: '02',
    chapterLabel: '案例素材',
    points: ['先看懂事实原貌', '压缩案例服务观点', '标注案例适用场景'],
    exercise: '把一个案例改写成80字论据，并写明它能证明的观点。',
  },
  {
    route: 'shenlun-writing',
    chapterId: 'writing-terms',
    chapterNo: '03',
    chapterLabel: '规范用词',
    points: ['识别口语化表达', '改成准确规范措辞', '把句子写短写清'],
    exercise: '从旧答案中挑五个口语词，逐个改成规范表达并重写原句。',
  },
  {
    route: 'shenlun-writing',
    chapterId: 'writing-metaphors',
    chapterNo: '04',
    chapterLabel: '比喻词库',
    points: ['理解比喻关系', '检索而不是硬背', '判断使用边界'],
    exercise: '检索一个常用比喻，写一句适用句和一句不宜使用的场景说明。',
  },
  {
    route: 'shenlun-writing',
    chapterId: 'writing-patterns',
    chapterNo: '05',
    chapterLabel: '常用句式',
    points: ['按表达功能积累', '看懂句式骨架', '结合例句仿写迁移'],
    exercise: '选一个句式骨架，围绕当前热点仿写两句并标出功能。',
  },
  {
    route: 'shenlun-writing',
    chapterId: 'writing-sentences',
    chapterNo: '06',
    chapterLabel: '主题佳句',
    points: ['按主题和用途积累', '区分判断过渡收束', '避免孤立背句'],
    exercise: '为一个主题各选一句开头、过渡和收束句，改写进同一段。',
  },
  {
    route: 'shenlun-writing',
    chapterId: 'writing-quotes',
    chapterNo: '07',
    chapterLabel: '名人箴言',
    points: ['连同出处一起记', '理解适用语境', '注意使用边界'],
    exercise: '选一句引语，写出出处、可用主题和一个不适合套用的情境。',
  },
  {
    route: 'shenlun-writing',
    chapterId: 'writing-essay',
    chapterNo: '08',
    chapterLabel: '作文框架',
    points: ['沿六个环节搭骨架', '先稳住中心论点', '让论据服务结构推进'],
    exercise: '用标题、开头、总论点、三个分论点列出一篇文章提纲。',
  },
  {
    route: 'shenlun-videos',
    chapterId: 'shenlun-video-course',
    chapterNo: '01',
    chapterLabel: '课程精讲',
    points: ['回看题型方法', '记录材料阅读提醒', '把表达方法放回真题'],
    exercise: '看一段精讲前先列提纲，结束后只补一条最有用的方法提醒。',
  },
  {
    route: 'shenlun-videos',
    chapterId: 'shenlun-video-classroom',
    chapterNo: '02',
    chapterLabel: '课堂实录',
    points: ['观察讲题与追问', '看现场修改过程', '记录学员卡点变化'],
    exercise: '选一段课堂实录，写下原答案问题、修改动作和重做后的变化。',
  },
  {
    route: 'shenlun-videos',
    chapterId: 'shenlun-video-worklog',
    chapterNo: '03',
    chapterLabel: '工作日常',
    points: ['了解备课批改流程', '观察选题和资料整理', '学习课后复盘习惯'],
    exercise: '看一个工作片段，整理出一条可用于自己复盘的检查项。',
  },
  {
    route: 'shenlun-videos',
    chapterId: 'shenlun-video-notes',
    chapterNo: '04',
    chapterLabel: '碎片分享',
    points: ['抓住一个表达提醒', '识别一处热点角度', '记录一个常见误区'],
    exercise: '看完一段碎片内容，把提醒改写成下一道题前的自检句。',
  },
  {
    route: 'interview-methods',
    chapterId: 'interview-methods-map',
    chapterNo: '01',
    chapterLabel: '题型地图',
    points: ['区分六类常见题型', '先确认身份对象任务', '按题型选择展开顺序'],
    exercise: '抽六道题，分别标出题型、核心矛盾和第一句话判断。',
  },
  {
    route: 'interview-methods',
    chapterId: 'interview-methods-flow',
    chapterNo: '02',
    chapterLabel: '训练流程',
    points: ['圈出题干限制', '先定两三个关键词', '按因果递进流程排序'],
    exercise: '用一道题完成看题、定重点、搭顺序、回听四步记录。',
  },
  {
    route: 'interview-methods',
    chapterId: 'interview-methods-practice',
    chapterNo: '03',
    chapterLabel: '一题三遍',
    points: ['第一遍只列提纲', '第二遍完整作答', '第三遍按录音重答'],
    exercise: '同一道题练三遍，每遍后只写一个最需要调整的问题。',
  },
  {
    route: 'interview-methods',
    chapterId: 'interview-methods-check',
    chapterNo: '04',
    chapterLabel: '答后检查',
    points: ['检查任务是否完成', '判断顺序是否清楚', '删掉模板词和重复句'],
    exercise: '回听一次作答，按任务、顺序、例子、重复四项各写一句评价。',
  },
  {
    route: 'interview-questions',
    chapterId: 'interview-questions-map',
    chapterNo: '01',
    chapterLabel: '真题地图',
    points: ['按系统和地区归档', '观察题型组合变化', '比较场景表达偏好'],
    exercise: '选同一系统两年真题，列出题型组合和场景差别。',
  },
  {
    route: 'interview-questions',
    chapterId: 'interview-questions-flow',
    chapterNo: '02',
    chapterLabel: '训练流程',
    points: ['读题判断任务', '关键词列提纲', '限时完整作答'],
    exercise: '按真实时长答一道题，记录一处内容问题和一处表达问题。',
  },
  {
    route: 'interview-questions',
    chapterId: 'interview-questions-index',
    chapterNo: '03',
    chapterLabel: '当前索引',
    points: ['从税务系统练起', '同一天题目连做', '跨年份观察命题变化'],
    exercise: '连续做同一天三道题，保存第一次提纲并写出整套节奏感受。',
  },
  {
    route: 'interview-questions',
    chapterId: 'interview-questions-review',
    chapterNo: '04',
    chapterLabel: '复盘清单',
    points: ['检查任务是否答全', '找出最空的一段', '确定下一次只改一事'],
    exercise: '复盘一段录音，只留下一个内容问题、一个表达问题和一次重答目标。',
  },
  {
    route: 'interview-expression',
    chapterId: 'interview-expression-map',
    chapterNo: '01',
    chapterLabel: '表达地图',
    points: ['先建立明确观点', '用结构组织内容', '让例证证明观点'],
    exercise: '选一道题，写出第一句话判断、两个层次和一个短例子。',
  },
  {
    route: 'interview-expression',
    chapterId: 'interview-expression-flow',
    chapterNo: '02',
    chapterLabel: '四段训练',
    points: ['30秒练观点开头', '60秒补例子场景', '120秒完整控制层次'],
    exercise: '选同一题说三遍，最后删掉重复句。',
  },
  {
    route: 'interview-expression',
    chapterId: 'interview-expression-daily',
    chapterNo: '03',
    chapterLabel: '每日小练',
    points: ['十分钟保持口感', '只练开头结构例子', '短练习便于坚持'],
    exercise: '每天找一道题，说30秒观点、1分钟结构，再补一个具体例子。',
  },
  {
    route: 'interview-expression',
    chapterId: 'interview-expression-review',
    chapterNo: '04',
    chapterLabel: '回听重点',
    points: ['听第一句话是否清楚', '找长句和重复词', '检查结尾是否突然收住'],
    exercise: '回听一段录音，圈出最长的一句话并改成两句自然表达。',
  },
  {
    route: 'interview-videos',
    chapterId: 'interview-videos-map',
    chapterNo: '01',
    chapterLabel: '影像档案',
    points: ['区分精讲实录讲评', '按主题回看课程片段', '从系列索引续看相关内容'],
    exercise: '选一个视频栏目，写下它对应的训练目标和下一段要看的内容。',
  },
  {
    route: 'interview-videos',
    chapterId: 'interview-videos-flow',
    chapterNo: '02',
    chapterLabel: '观看流程',
    points: ['先自己想一分钟', '只记判断结构金句', '关掉视频重答一次'],
    exercise: '看讲解前先口述提纲，关掉视频后用自己的话重答一遍。',
  },
  {
    route: 'interview-videos',
    chapterId: 'interview-videos-class',
    chapterNo: '03',
    chapterLabel: '看课堂',
    points: ['重点看修改过程', '记录老师追问', '比较第二遍变化'],
    exercise: '看一段课堂实录，写出原回答卡点、追问内容和改动句子。',
  },
  {
    route: 'interview-videos',
    chapterId: 'interview-videos-notes',
    chapterNo: '04',
    chapterLabel: '课后笔记',
    points: ['每段视频留一条', '区分审题和结构动作', '记录可重答题目'],
    exercise: '看完一段视频，只写一个审题提醒、一句自然表达和一道重答题。',
  },
] as const satisfies readonly LearningReadingGuideEntry[];

const guideByChapterId: ReadonlyMap<string, LearningReadingGuideEntry> = new Map(
  learningReadingGuides.map((entry) => [entry.chapterId, entry]),
);

export function getLearningReadingGuide(activeId: string) {
  return guideByChapterId.get(activeId) ?? null;
}
